// Generated from Postales.csv. Keep one entry per specific trip route.
// The source currently provides Spanish copy; pick() falls back to ES on untranslated locales.
export const JOURNEY_POSTCARDS = {
  tourDesiertoAtlas45: {
    sourcePath: "/viajes/desierto_atlas/programa_4n_5d",
    paragraphs: [
      { es: "Imagina despertar rodeado por las dunas del Sáhara, cuando las primeras luces del día empiezan a transformar el paisaje." },
      { es: "Este viaje te lleva al sur de Marruecos, desde las puertas del desierto hasta los paisajes del Alto Atlas. Recorrerás pistas en 4x4, descubrirás oasis y poblados, y conocerás lugares como Khamlia y el mercado de Rissani." },
      { es: "Pero habrá un momento en el que tendrás que dejar atrás el vehículo." },
      { es: "Subirás a lomos de un dromedario para adentrarte en las dunas de Erg Chebbi, contemplar la puesta de sol y llegar a un bivouac donde pasarás la noche bajo las estrellas." },
      { es: "Y cuando parezca que el desierto lo ha mostrado todo, el paisaje volverá a cambiar." },
      { es: "Te esperan las Gargantas del Todra, el Valle del Dades y las montañas del Alto Atlas antes de llegar a Ouarzazate." },
      { es: "Cinco días para descubrir algunos de los paisajes y experiencias que hacen del sur de Marruecos un lugar difícil de olvidar." },
    ],
    closing: { es: "¿Preparado para vivirlo?" },
  },
  tourDesiertoAtlas56: {
    sourcePath: "/viajes/desierto_atlas/programa_5n_6d",
    paragraphs: [
      { es: "Imagina adentrarte en el Sáhara y, unos días después, encontrarte recorriendo las montañas del Alto Atlas." },
      { es: "Este viaje te invita a descubrir dos paisajes completamente diferentes del sur de Marruecos." },
      { es: "Primero, el desierto. Recorrerás pistas en 4x4, descubrirás oasis y poblados y llegarás hasta las inmensas dunas de Erg Chebbi. Allí, cambiarás el vehículo por un dromedario para adentrarte entre la arena, contemplar la puesta de sol y pasar una noche en un bivouac bajo las estrellas." },
      { es: "Al amanecer, el viaje continúa por Khamlia y Rissani antes de dejar atrás el Sáhara." },
      { es: "Entonces, el paisaje cambia." },
      { es: "Te esperan las Gargantas del Todra, el Valle del Dades y las pistas del Alto Atlas Central, entre poblados como Boutaghrar y Amskar y las Gargantas del M'Goun." },
      { es: "Seis días entre desierto, oasis, gargantas y montañas." },
    ],
    closing: { es: "Un viaje para descubrir cuánto puede cambiar Marruecos en apenas unos kilómetros. ¿Te imaginas viviéndolo?" },
  },
  tourDesiertoAtlas67: {
    sourcePath: "/viajes/desierto_atlas/programa_6n_7d",
    paragraphs: [
      { es: "Hay viajes que te llevan a un lugar. Y otros que te invitan a sentirlo sin prisas." },
      { es: "Durante siete días, el sur de Marruecos irá cambiando ante tus ojos. Primero llegará el Sáhara: pistas en 4x4, oasis y las inmensas dunas de Erg Chebbi." },
      { es: "Al caer la tarde, cambiarás el 4x4 por un dromedario para adentrarte en las dunas, contemplar la puesta de sol y pasar una noche en un bivouac, bajo las estrellas." },
      { es: "Y al amanecer, el desierto seguirá revelándose: Merdani, las minas de M'Fis, la música Gnawa de Khamlia y el mercado tradicional de Rissani." },
      { es: "Después, el horizonte volverá a transformarse." },
      { es: "Las Gargantas del Todra, el Valle del Dades y las pistas del Alto Atlas Central te conducirán entre Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Siete días para pasar del silencio del Sáhara a la inmensidad de las montañas." },
    ],
    closing: { es: "¿Te imaginas estar allí?" },
  },
  tourAtlasDesierto45: {
    sourcePath: "/viajes/atlas_desierto/programa_4n_5d",
    paragraphs: [
      { es: "Imagina comenzar entre las montañas del Alto Atlas… y terminar caminando sobre las dunas del Sáhara." },
      { es: "Este viaje es una transformación constante del paisaje." },
      { es: "Desde Boumalne Dades, te adentrarás en el Alto Atlas Central por pistas que conducen hasta poblados bereberes como Boutaghrar. Atravesarás montañas, valles y las impresionantes Gargantas del Todra antes de alcanzar Erfoud, la puerta del desierto." },
      { es: "Y entonces, el horizonte cambia por completo." },
      { es: "El 4x4 te llevará entre pistas, oasis y paisajes desérticos hasta las grandes dunas de Erg Chebbi. Allí subirás a un dromedario para contemplar la puesta de sol y llegar a un bivouac donde pasarás la noche bajo las estrellas." },
      { es: "Al amanecer, todavía quedarán Khamlia, su música Gnawa, el mercado de Rissani y el inmenso palmeral del Valle del Ziz." },
      { es: "Cinco días para viajar de las montañas del Atlas al corazón del Sáhara." },
    ],
    closing: { es: "¿Preparado para vivirlo?" },
  },
  tourAtlasDesierto56: {
    sourcePath: "/viajes/atlas_desierto/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar entre las montañas del Alto Atlas y, seis días después, llevarte contigo el recuerdo de una noche bajo las estrellas del Sáhara." },
      { es: "El viaje empieza entre valles, pistas de montaña y poblados bereberes. Recorrerás el Alto Atlas Central, descubrirás Boutaghrar y Amskar, las Gargantas del M'Goun y las grutas donde todavía habitan familias nómadas." },
      { es: "Poco a poco, el paisaje irá cambiando." },
      { es: "El Valle del Dades, las Gargantas del Todra y Erfoud marcarán el camino hacia el desierto." },
      { es: "Y entonces aparecerá Erg Chebbi." },
      { es: "Dejarás atrás el 4x4 para subir a un dromedario, adentrarte entre las dunas, contemplar la puesta de sol y llegar a un bivouac donde pasarás la noche bajo las estrellas." },
      { es: "Al amanecer te esperan Khamlia, la música Gnawa y el mercado de Rissani, antes de despedirte del sur contemplando el Valle del Ziz." },
    ],
    closing: { es: "De las montañas a las dunas. Seis días para vivir dos mundos en un mismo viaje." },
  },
  tourAtlasDesierto67: {
    sourcePath: "/viajes/atlas_desierto/programa_6n_7d",
    paragraphs: [
      { es: "Imagina un viaje en el que cada día el horizonte cambia un poco más… hasta que las montañas desaparecen y ante ti solo quedan las dunas del Sáhara." },
      { es: "Durante siete días recorrerás el sur de Marruecos desde el Alto Atlas hasta Erg Chebbi." },
      { es: "Atravesarás pistas de montaña, poblados como Boutaghrar y Amskar, las Gargantas del M'Goun, el Valle del Dades y las imponentes Gargantas del Todra." },
      { es: "Y entonces llegará el desierto." },
      { es: "Recorrerás antiguas pistas del Rally Dakar, descubrirás oasis y, al atardecer, subirás a un dromedario para adentrarte entre las dunas de Erg Chebbi y pasar la noche en un bivouac bajo las estrellas." },
      { es: "Al despertar, todavía te esperan Merdani, las minas de M'Fis, la música Gnawa de Khamlia y el mercado tradicional de Rissani." },
      { es: "Y como última imagen del viaje, el inmenso palmeral del Valle del Ziz." },
    ],
    closing: { es: "Siete días. De las montañas del Atlas al corazón del Sáhara. ¿Te imaginas viviéndolo?" },
  },
  tourMarrakechErg45: {
    sourcePath: "/viajes/marrakech_ergchebbi/programa_4n_5d",
    paragraphs: [
      { es: "Imagina comenzar entre el bullicio, los colores y los aromas de Marrakech… y terminar contemplando el silencio del Sáhara bajo un cielo lleno de estrellas." },
      { es: "Este viaje te lleva de un Marruecos a otro en solo cinco días." },
      { es: "Caminarás por la Medina de Marrakech, entre la Koutoubia, el Palacio de la Bahía, sus zocos y la inconfundible Djemaa el-Fna." },
      { es: "Después, dejarás atrás la ciudad para cruzar el Alto Atlas, atravesar el Tizi n'Tichka y descubrir Aït Ben Haddou antes de continuar hacia el Valle de las Rosas y Boumalne Dades." },
      { es: "Las Gargantas del Todra anunciarán que el desierto está cada vez más cerca." },
      { es: "Y finalmente, Erg Chebbi." },
      { es: "Subirás a un dromedario al atardecer, te adentrarás entre las dunas y pasarás la noche en un bivouac bajo las estrellas." },
    ],
    closing: { es: "De la energía de Marrakech al silencio del Sáhara. Cinco días para descubrir algunos de los grandes contrastes del sur de Marruecos." },
  },
  tourMarrakechErg56: {
    sourcePath: "/viajes/marrakech_ergchebbi/programa_5n_6d",
    paragraphs: [
      { es: "Hay lugares que se descubren con la vista. Otros, con todos los sentidos." },
      { es: "Este viaje comienza en Marrakech, entre el movimiento de Djemaa el-Fna, las callejuelas de la Medina, los zocos, la Koutoubia y el Palacio de la Bahía." },
      { es: "Después, la ciudad queda atrás y comienza el camino hacia el Sáhara." },
      { es: "Cruzarás el Alto Atlas por el Tizi n'Tichka, descubrirás Aït Ben Haddou y atravesarás paisajes como el Valle de las Rosas y las Gargantas del Todra." },
      { es: "Hasta que, finalmente, aparezcan las dunas de Erg Chebbi." },
      { es: "Allí cambiarás el 4x4 por un dromedario para contemplar la puesta de sol y pasar una noche en un bivouac bajo las estrellas." },
      { es: "Al amanecer, el viaje continuará por Merdani, Khamlia y el mercado de Rissani, antes de despedirte contemplando el Valle del Ziz." },
    ],
    closing: { es: "Seis días para sentir cómo Marruecos cambia a cada paso: de Marrakech al corazón del Sáhara." },
  },
  tourMarrakechErg67: {
    sourcePath: "/viajes/marrakech_ergchebbi/programa_6n_7d",
    paragraphs: [
      { es: "Imagina empezar rodeado por los colores, los aromas y la energía de Marrakech… y terminar contemplando el amanecer desde las dunas del Sáhara." },
      { es: "Durante siete días, este viaje te mostrará cómo Marruecos puede transformarse ante tus ojos." },
      { es: "Descubrirás la Medina, la Koutoubia, el Palacio de la Bahía y los zocos de Marrakech antes de poner rumbo al Alto Atlas." },
      { es: "Cruzarás el Tizi n'Tichka, descubrirás Aït Ben Haddou y continuarás entre el Valle de las Rosas, Boutaghrar, el Valle del Dadès y las Gargantas del Todra." },
      { es: "Poco a poco, las montañas quedarán atrás." },
      { es: "En Erg Chebbi cambiarás el 4x4 por un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Después llegarán el amanecer, Khamlia, la música Gnawa y el mercado de Rissani." },
    ],
    closing: { es: "Siete días. De la intensidad de Marrakech a la inmensidad del Sáhara. Un viaje para vivir Marruecos a través de todos sus contrastes." },
  },
  tourMarrakechErg78: {
    sourcePath: "/viajes/marrakech_ergchebbi/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre los colores, los aromas y la energía de Marrakech… y, unos días después, contemplar cómo el sol desaparece tras las dunas del Sáhara." },
      { es: "Este viaje es una invitación a descubrir el sur de Marruecos sin prisas." },
      { es: "Desde la Medina, la Koutoubia y los zocos de Marrakech, cruzarás el Alto Atlas para descubrir Aït Ben Haddou y continuar entre paisajes de montaña hacia Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Después llegarán el Valle del Dadès y las Gargantas del Todra, mientras el paisaje anuncia que el desierto está cada vez más cerca." },
      { es: "Hasta alcanzar Erg Chebbi." },
      { es: "Allí cambiarás el 4x4 por un dromedario, te adentrarás entre las dunas al atardecer y pasarás una noche bajo las estrellas." },
      { es: "Y al amanecer, todavía quedarán Khamlia, la música Gnawa, Rissani y el Valle del Ziz." },
    ],
    closing: { es: "Ocho días para dejar atrás lo cotidiano y descubrir, paisaje a paisaje, la magia del sur de Marruecos." },
  },
  tourErgMarrakech45: {
    sourcePath: "/viajes/ergchebbi_marrakech/programa_4n_5d",
    paragraphs: [
      { es: "Imagina que tu viaje comienza donde muchos sueñan con llegar: frente a las dunas del Sáhara." },
      { es: "Desde Erfoud te adentrarás en el desierto recorriendo pistas en 4x4, poblados y oasis, hasta que aparezcan las grandes dunas de Erg Chebbi." },
      { es: "Al atardecer cambiarás el vehículo por un dromedario y avanzarás entre la arena hasta contemplar la puesta de sol y pasar una noche en un bivouac, bajo las estrellas." },
      { es: "Pero el viaje no termina en el desierto." },
      { es: "Las Gargantas del Todra y el Valle del Dadès te conducirán hacia las montañas del Alto Atlas. En el camino descubrirás Aït Ben Haddou y cruzarás el Tizi n'Tichka antes de llegar a un mundo completamente diferente." },
      { es: "Marrakech." },
      { es: "Su Medina, la Koutoubia, el Palacio de la Bahía, sus zocos y Djemaa el-Fna pondrán el broche final." },
    ],
    closing: { es: "Cinco días. Del silencio del Sáhara a la energía de Marrakech." },
  },
  tourErgMarrakech56: {
    sourcePath: "/viajes/ergchebbi_marrakech/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar el viaje entre las dunas del Sáhara… y terminar perdiéndote entre los colores y los zocos de Marrakech." },
      { es: "Durante seis días, el paisaje irá transformándose a tu alrededor." },
      { es: "Recorrerás pistas del desierto en 4x4, descubrirás oasis y llegarás hasta las dunas de Erg Chebbi. Allí subirás a un dromedario para contemplar la puesta de sol y pasar una noche en un bivouac bajo las estrellas." },
      { es: "Al amanecer, el Sáhara todavía tendrá mucho que mostrarte: Merdani, la música Gnawa de Khamlia y el mercado tradicional de Rissani." },
      { es: "Después, las dunas darán paso a las Gargantas del Todra, el Valle del Dadès y las montañas del Alto Atlas." },
      { es: "Descubrirás Aït Ben Haddou, cruzarás el Tizi n'Tichka y, finalmente, llegarás a Marrakech." },
    ],
    closing: { es: "Seis días para viajar del silencio del desierto a la energía de la ciudad roja. Dos mundos, un solo viaje." },
  },
  tourErgMarrakech67: {
    sourcePath: "/viajes/ergchebbi_marrakech/programa_6n_7d",
    paragraphs: [
      { es: "Imagina despertar entre las dunas del Sáhara… y terminar, siete días después, caminando entre los zocos y la energía de Marrakech." },
      { es: "El viaje comienza adentrándote en el desierto. Recorrerás pistas en 4x4, descubrirás oasis y llegarás hasta Erg Chebbi, donde subirás a un dromedario para contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Al amanecer, el Sáhara te llevará hasta Merdani, Khamlia y la música Gnawa, antes de descubrir el mercado tradicional de Rissani." },
      { es: "Después, el paisaje cambiará por completo." },
      { es: "Las Gargantas del Todra y el Valle del Dadès abrirán el camino hacia el Alto Atlas, entre Boutaghrar, Amskar, familias nómadas y las Gargantas del M'Goun." },
      { es: "Finalmente, Aït Ben Haddou y el Tizi n'Tichka te conducirán hasta Marrakech." },
    ],
    closing: { es: "Siete días para viajar de la inmensidad del Sáhara al corazón de la ciudad roja, descubriendo todos los mundos que existen entre ambos." },
  },
  tourErgMarrakech78: {
    sourcePath: "/viajes/ergchebbi_marrakech/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre el silencio y la inmensidad del Sáhara… y terminar rodeado por los colores, los aromas y la vida de Marrakech." },
      { es: "Durante ocho días, este viaje te llevará de un Marruecos a otro." },
      { es: "Te adentrarás en Erg Chebbi en dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer, descubrirás Merdani, Khamlia y su música Gnawa, y el mercado de Rissani." },
      { es: "Después, el desierto quedará atrás para dar paso a las Gargantas del Todra, el Valle del Dadès y las montañas del Alto Atlas, recorriendo Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka marcarán el camino hacia Marrakech." },
      { es: "Y allí te esperan la Medina, la Koutoubia, el Palacio de la Bahía, los zocos y Djemaa el-Fna." },
    ],
    closing: { es: "Ocho días para descubrir cómo un mismo viaje puede llevarte del silencio absoluto del desierto a la energía de una de las ciudades más fascinantes de Marruecos." },
  },
  tourMarrakechLoop23: {
    sourcePath: "/viajes/marrakech_ergchebbi_marrakech/programa_2n_3d",
    paragraphs: [
      { es: "¿Y si solo necesitaras tres días para cambiar por completo de paisaje?" },
      { es: "Desde Marrakech, este viaje te llevará a cruzar las montañas del Alto Atlas por el Tizi n'Tichka, descubrir Aït Ben Haddou y continuar entre Ouarzazate y el Valle de las Rosas hasta Boumalne Dades." },
      { es: "Pero el gran momento todavía estará por llegar." },
      { es: "Tras conocer Tinerhir y las Gargantas del Todra, dejarás atrás las montañas para adentrarte en el Sáhara." },
      { es: "En Erg Chebbi cambiarás el 4x4 por un dromedario y avanzarás entre las dunas mientras cae el sol, hasta llegar al bivouac donde pasarás la noche bajo las estrellas." },
      { es: "Y al amanecer, subirás de nuevo a las dunas para contemplar cómo despierta el desierto antes de emprender el regreso a Marrakech." },
    ],
    closing: { es: "Tres días. Montañas, kasbahs, gargantas y Sáhara. Una escapada breve, pero difícil de olvidar." },
  },
  tourMarrakechLoop34: {
    sourcePath: "/viajes/marrakech_ergchebbi_marrakech/programa_3n_4d",
    paragraphs: [
      { es: "Imagina dejar atrás Marrakech y, en apenas unos días, encontrarte contemplando el atardecer desde las dunas del Sáhara." },
      { es: "El camino ya forma parte de la aventura." },
      { es: "Cruzarás el Alto Atlas por el Tizi n'Tichka, descubrirás Aït Ben Haddou y continuarás por Ouarzazate y el Valle de las Rosas hasta Boumalne Dades." },
      { es: "Después llegarán las Gargantas del Todra y, poco a poco, el paisaje se abrirá hacia el desierto." },
      { es: "En Erg Chebbi cambiarás el 4x4 por un dromedario para adentrarte entre las dunas, contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Al amanecer, el Sáhara seguirá sorprendiéndote con Merdani, la música Gnawa de Khamlia y el mercado de Rissani." },
      { es: "Y después de vivirlo, emprenderás el camino de regreso a Marrakech." },
    ],
    closing: { es: "Cuatro días para escapar de lo cotidiano y descubrir montañas, kasbahs, gargantas y la magia del Sáhara." },
  },
  tourMarrakechLoop45: {
    sourcePath: "/viajes/marrakech_ergchebbi_marrakech/programa_4n_5d",
    paragraphs: [
      { es: "Imagina dejar atrás Marrakech y ver cómo, kilómetro a kilómetro, el paisaje se transforma hasta convertirse en un inmenso mar de dunas." },
      { es: "Durante cinco días recorrerás algunos de los grandes contrastes del sur de Marruecos." },
      { es: "Cruzarás el Alto Atlas por el Tizi n'Tichka, descubrirás Aït Ben Haddou y te adentrarás entre montañas, pueblos bereberes y valles hasta llegar a Boutaghrar, el Valle del Dadès y las Gargantas del Todra." },
      { es: "Y entonces llegará el Sáhara." },
      { es: "Recorrerás antiguas pistas del Rally Dakar, conocerás poblados y nómadas del desierto y alcanzarás las dunas de Erg Chebbi. Allí subirás a un dromedario para contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Al amanecer, todavía te esperan Merdani, la música Gnawa de Khamlia y el mercado de Rissani." },
    ],
    closing: { es: "Cinco días para descubrir que entre Marrakech y el Sáhara hay todo un mundo esperando ser vivido." },
  },
  tourMarrakechLoop56: {
    sourcePath: "/viajes/marrakech_ergchebbi_marrakech/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar entre los colores, los aromas y la energía de Marrakech… y, unos días después, despertar rodeado por las dunas del Sáhara." },
      { es: "Este viaje te invita a vivir dos caras completamente diferentes de Marruecos." },
      { es: "Primero, la Medina de Marrakech: la Koutoubia, el Palacio de la Bahía, sus zocos y la inconfundible Djemaa el-Fna." },
      { es: "Después comienza la aventura." },
      { es: "Cruzarás el Alto Atlas por el Tizi n'Tichka, descubrirás Aït Ben Haddou y continuarás hasta las Gargantas del Todra, mientras el paisaje cambia y el desierto se acerca." },
      { es: "En Erg Chebbi dejarás atrás el 4x4 para adentrarte entre las dunas en dromedario, contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Al amanecer, subirás de nuevo a las dunas antes de iniciar el camino de regreso a Marrakech." },
    ],
    closing: { es: "Seis días para pasar del corazón de la ciudad roja al silencio del Sáhara… y volver con Marruecos un poco más dentro de ti." },
  },
  tourMarrakechLoop67: {
    sourcePath: "/viajes/marrakech_ergchebbi_marrakech/programa_6n_7d",
    paragraphs: [
      { es: "Hay viajes en los que el paisaje cambia. Y otros en los que parece que has viajado a mundos completamente distintos." },
      { es: "Este comienza en Marrakech, entre la energía de Djemaa el-Fna, la Medina, la Koutoubia, el Palacio de la Bahía y sus zocos." },
      { es: "Después, la ciudad queda atrás." },
      { es: "Cruzarás el Alto Atlas por el Tizi n'Tichka, descubrirás Aït Ben Haddou y continuarás hacia las Gargantas del Todra, hasta que las montañas den paso al Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario para adentrarte entre las dunas, contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Y cuando llegue el amanecer, el desierto todavía tendrá mucho que mostrarte: Merdani, la música Gnawa de Khamlia y el mercado de Rissani." },
    ],
    closing: { es: "Siete días para sentir los contrastes de Marruecos: de la intensidad de Marrakech al silencio infinito del Sáhara… y de vuelta." },
  },
  tourMarrakechLoop78: {
    sourcePath: "/viajes/marrakech_ergchebbi_marrakech/programa_7n_8d",
    paragraphs: [
      { es: "Imagina un viaje en el que cada día Marruecos te muestra una cara diferente." },
      { es: "Comenzarás entre los colores, los aromas y la energía de Marrakech, recorriendo su Medina, la Koutoubia, el Palacio de la Bahía y sus zocos." },
      { es: "Después, dejarás atrás la ciudad para cruzar el Alto Atlas, descubrir Aït Ben Haddou y adentrarte entre pueblos bereberes, el Valle del Dadès y las Gargantas del Todra." },
      { es: "Hasta que el horizonte se abra y aparezca el Sáhara." },
      { es: "Recorrerás antiguas pistas del Rally Dakar, oasis y poblados del desierto antes de llegar a Erg Chebbi. Allí subirás a un dromedario para contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Al amanecer te esperan Merdani, la música Gnawa de Khamlia y el mercado de Rissani." },
    ],
    closing: { es: "Ocho días para descubrir Marruecos sin prisas, desde la intensidad de Marrakech hasta el silencio de las dunas. Un viaje para vivirlo, sentirlo y recordarlo." },
  },
  tourMarrakechEss45: {
    sourcePath: "/viajes/marrakech_essaouira/programa_4n_5d",
    paragraphs: [
      { es: "Imagina comenzar entre el movimiento, los colores y los aromas de Marrakech… y terminar escuchando las olas del Atlántico frente a las murallas de Essaouira." },
      { es: "Este viaje une dos formas muy diferentes de sentir Marruecos." },
      { es: "Primero, la energía de Marrakech. Recorrerás su Medina, descubrirás la Koutoubia y el Palacio de la Bahía, y te perderás entre zocos, artesanos y el ambiente de Djemaa el-Fna." },
      { es: "Después, el ritmo cambia." },
      { es: "Te espera Essaouira, con su medina amurallada, su puerto pesquero, sus galerías de arte y ese ambiente atlántico que invita a caminar sin prisas." },
      { es: "Tendrás tiempo para pasear por la playa, recorrer la Skala, perderte por las calles de la medina o simplemente sentarte frente al océano." },
    ],
    closing: { es: "Cinco días para descubrir dos almas de Marruecos: la energía de Marrakech y la calma de Essaouira." },
  },
  tourMarrakechEss67: {
    sourcePath: "/viajes/marrakech_essaouira/programa_6n_7d",
    paragraphs: [
      { es: "Imagina un viaje que comienza entre el bullicio de una medina y termina con la mirada perdida en el Atlántico." },
      { es: "Durante siete días descubrirás dos formas completamente diferentes de sentir Marruecos." },
      { es: "Primero, Marrakech. Djemaa el-Fna, la Koutoubia, el Palacio de la Bahía, sus zocos y artesanos te sumergirán en una ciudad llena de vida. Y tendrás tiempo para seguir explorándola a tu manera." },
      { es: "Después, el ritmo cambia." },
      { es: "Llegarás a Essaouira, donde te esperan el puerto pesquero, la medina amurallada, las galerías de arte y la brisa del océano." },
      { es: "Aquí no hay prisa. Podrás caminar por la playa, recorrer la Skala, perderte por la medina, practicar deportes acuáticos o simplemente disfrutar de una terraza frente al Atlántico." },
    ],
    closing: { es: "Siete días entre energía y calma, entre zocos y océano. Dos ciudades, dos ritmos y un Marruecos que invita a disfrutar cada momento." },
  },
  tourFezAtlasErr56: {
    sourcePath: "/viajes/fez-atlas-errachidia/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas de Fez… y, unos días después, contemplar el atardecer desde las dunas del Sáhara." },
      { es: "Este viaje es una transformación constante." },
      { es: "Desde la Medina de Fez, sus zocos, palacios y talleres artesanales, pondrás rumbo al Medio Atlas, atravesando Ifrane y sus bosques de cedros hasta llegar al lago Aguelmame Sidi Ali." },
      { es: "Después, las montañas abrirán paso al inmenso palmeral del Valle del Ziz y a Erfoud, la puerta del desierto." },
      { es: "Y entonces llegará Erg Chebbi." },
      { es: "Recorrerás pistas, poblados y oasis antes de subir a un dromedario, adentrarte entre las dunas y pasar una noche bajo las estrellas." },
      { es: "Al amanecer, todavía te esperan Merdani, la música Gnawa de Khamlia y el mercado de Rissani." },
    ],
    closing: { es: "Seis días para viajar desde el corazón histórico de Fez hasta el silencio del Sáhara. Un Marruecos de medinas, bosques, montañas, oasis y dunas." },
  },
  tourFezRak67: {
    sourcePath: "/viajes/gransur/fez_marrakech/programa_6n_7d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas de Fez… y terminar, siete días después, entre los colores y la energía de Marrakech." },
      { es: "Entre ambas ciudades, te espera todo un viaje por Marruecos." },
      { es: "Atravesarás Ifrane y los bosques de cedros del Medio Atlas, contemplarás el inmenso palmeral del Valle del Ziz y llegarás hasta las puertas del Sáhara." },
      { es: "En Erg Chebbi cambiarás el 4x4 por un dromedario para adentrarte entre las dunas, contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Después del amanecer llegarán Khamlia y Rissani, antes de dejar atrás el desierto para descubrir las Gargantas del Todra y el Valle del Dadès." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka marcarán el camino final hacia Marrakech." },
    ],
    closing: { es: "Siete días para cruzar Marruecos de una ciudad imperial a otra, entre medinas, bosques, oasis, dunas y montañas. Un viaje que cambia de paisaje a cada etapa." },
  },
  tourFezRak78: {
    sourcePath: "/viajes/gransur/fez_marrakech/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez y terminar, ocho días después, contemplando la vida de Djemaa el-Fna en Marrakech." },
      { es: "Entre ambas ciudades, Marruecos se transforma ante tus ojos." },
      { es: "Atravesarás Ifrane y los bosques de cedros, contemplarás el inmenso palmeral del Valle del Ziz y llegarás hasta las puertas del Sáhara." },
      { es: "En Erg Chebbi dejarás atrás el 4x4 para adentrarte entre las dunas en dromedario, contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Después llegarán Khamlia, Rissani, las Gargantas del Todra y el Valle del Dadès." },
      { es: "Y cuando creas haberlo visto todo, Aït Ben Haddou y el Tizi n'Tichka abrirán el camino hacia Marrakech, donde te esperan la Koutoubia, el Palacio de la Bahía, los zocos y Djemaa el-Fna." },
    ],
    closing: { es: "Ocho días para atravesar Marruecos y sentir cómo cada paisaje, cada ciudad y cada encuentro forman parte de un mismo viaje inolvidable." },
  },
  tourFezRak89: {
    sourcePath: "/viajes/gransur/fez_marrakech/programa_8n_9d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez y terminar, nueve días después, sintiendo la energía de Marrakech." },
      { es: "Entre ambas ciudades, te espera un Marruecos que cambia a cada etapa." },
      { es: "Atravesarás Ifrane, los bosques de cedros y el inmenso palmeral del Valle del Ziz antes de alcanzar el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario para adentrarte entre las dunas, contemplar la puesta de sol y pasar una noche bajo las estrellas." },
      { es: "Después llegarán Khamlia, Rissani y las Gargantas del Todra, antes de adentrarte en las montañas del Alto Atlas Central, entre Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka marcarán el camino hacia Marrakech, con su Medina, la Koutoubia, el Palacio de la Bahía y Djemaa el-Fna." },
    ],
    closing: { es: "Nueve días para atravesar Marruecos entre ciudades imperiales, desierto y montañas. Un viaje para sentir cómo el paisaje cambia… y tú con él." },
  },
  tourFezRak910: {
    sourcePath: "/viajes/gransur/fez_marrakech/programa_9n_10d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez y terminar, diez días después, entre los colores y la energía de Marrakech." },
      { es: "Entre ambas ciudades te espera un viaje que transforma el paisaje a cada paso." },
      { es: "Atravesarás el Medio Atlas, los bosques de cedros y el Valle del Ziz antes de alcanzar el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Y esta vez, el desierto se vive sin prisas: el amanecer sobre las dunas, Merdani, la música Gnawa de Khamlia y el mercado de Rissani." },
      { es: "Después llegarán las Gargantas del Todra, el Valle del Dadès y el Alto Atlas Central, entre Boutaghrar, Amskar y M'Goun." },
      { es: "Finalmente, Aït Ben Haddou y el Tizi n'Tichka te conducirán hasta Marrakech." },
    ],
    closing: { es: "Diez días para atravesar Marruecos sin prisas, del corazón de Fez al de Marrakech, dejando que cada paisaje se convierta en parte del recuerdo." },
  },
  tourFezSidialiRak78: {
    sourcePath: "/viajes/gransur/fez_sidiali_marrakech/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez, despertar junto a un lago en pleno Atlas… y, unos días después, contemplar el atardecer entre las dunas del Sáhara." },
      { es: "Este viaje es una sucesión de contrastes." },
      { es: "Desde Fez cruzarás el Medio Atlas, pasando por Ifrane y sus bosques de cedros, hasta llegar al lago Aguelmame Sidi Ali." },
      { es: "Después, el paisaje volverá a transformarse. El Valle del Ziz te conducirá hacia Erfoud y las puertas del desierto." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol y pasarás una noche bajo las estrellas." },
      { es: "El camino continuará por Khamlia, Rissani, las Gargantas del Todra y el Valle del Dadès, antes de descubrir Aït Ben Haddou y cruzar el Tizi n'Tichka." },
      { es: "Y al final, Marrakech." },
    ],
    closing: { es: "Ocho días para viajar entre medinas, lagos, montañas, oasis y dunas. Un Marruecos lleno de contrastes que cambia ante tus ojos." },
  },
  tourFezSidialiRak89: {
    sourcePath: "/viajes/gransur/fez_sidiali_marrakech/programa_8n_9d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez, despertar junto a un lago en las montañas y, unos días después, dormir entre las dunas del Sáhara." },
      { es: "Durante nueve días, Marruecos irá cambiando ante tus ojos." },
      { es: "Cruzarás el Medio Atlas, Ifrane y sus bosques de cedros hasta llegar al lago Aguelmame Sidi Ali. Desde allí, el Valle del Ziz te conducirá hacia Erfoud y las puertas del desierto." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Después llegarán Khamlia, Rissani, las Gargantas del Todra y el Valle del Dadès." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka abrirán finalmente el camino hacia Marrakech, con su Medina, la Koutoubia, el Palacio de la Bahía, sus zocos y Djemaa el-Fna." },
    ],
    closing: { es: "Nueve días entre ciudades, lagos, montañas, oasis y desierto. Un viaje para descubrir cuántos Marruecos caben dentro de un solo país." },
  },
  tourFezSidialiRak910: {
    sourcePath: "/viajes/gransur/fez_sidiali_marrakech/programa_9n_10d",
    paragraphs: [
      { es: "Imagina un viaje en el que cada amanecer parece pertenecer a un Marruecos diferente." },
      { es: "Comenzarás entre las callejuelas de Fez y cruzarás el Medio Atlas, entre Ifrane y bosques de cedros, hasta despertar junto al lago Aguelmame Sidi Ali." },
      { es: "Desde allí, el Valle del Ziz te conducirá hacia el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Después llegarán Khamlia, Rissani y las Gargantas del Todra, antes de adentrarte en el Alto Atlas Central, entre Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka marcarán el camino final hacia Marrakech." },
    ],
    closing: { es: "Diez días entre medinas, lagos, oasis, dunas y montañas. Un viaje para descubrir un Marruecos que cambia a cada paso y que invita a seguir avanzando para descubrir qué hay detrás del próximo horizonte." },
  },
  tourMarrakechFez67: {
    sourcePath: "/viajes/gransur/marrakech_fez/programa_6n_7d",
    paragraphs: [
      { es: "Imagina comenzar entre los colores, los aromas y la energía de Marrakech… y terminar perdiéndote entre las callejuelas de Fez." },
      { es: "Entre ambas ciudades, te espera un viaje lleno de contrastes." },
      { es: "Cruzarás el Alto Atlas por el Tizi n'Tichka, descubrirás Aït Ben Haddou y continuarás entre el Valle del Dadès, Boutaghrar y las Gargantas del Todra hasta alcanzar las puertas del Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer, descubrirás Merdani, Khamlia y Rissani antes de emprender el camino hacia el norte." },
      { es: "El Valle del Ziz, Ifrane y sus bosques de cedros te conducirán finalmente hasta Fez y su fascinante Medina." },
    ],
    closing: { es: "Siete días para cruzar Marruecos de una ciudad imperial a otra, entre montañas, oasis y desierto. Un viaje donde cada nuevo horizonte parece pertenecer a un Marruecos diferente." },
  },
  tourMarrakechFez78: {
    sourcePath: "/viajes/gransur/marrakech_fez/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre los colores, los aromas y la energía de Marrakech… y terminar perdiéndote entre las callejuelas de Fez." },
      { es: "Durante ocho días, Marruecos cambiará de paisaje ante tus ojos." },
      { es: "Descubrirás la Medina de Marrakech, la Koutoubia, el Palacio de la Bahía y sus zocos antes de cruzar el Alto Atlas hacia Aït Ben Haddou, el Valle del Dadès y las Gargantas del Todra." },
      { es: "Después llegará el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer te esperan Merdani, Khamlia y Rissani, antes de poner rumbo al norte." },
      { es: "El Valle del Ziz, Ifrane y sus bosques de cedros te conducirán finalmente hasta la fascinante Medina de Fez." },
    ],
    closing: { es: "Ocho días para atravesar Marruecos entre ciudades imperiales, montañas, oasis y dunas. Un viaje en el que cada etapa abre la puerta a un mundo diferente." },
  },
  tourMarrakechFez89: {
    sourcePath: "/viajes/gransur/marrakech_fez/programa_8n_9d",
    paragraphs: [
      { es: "Imagina comenzar entre los colores y la energía de Marrakech… y terminar perdiéndote entre las callejuelas de Fez." },
      { es: "Entre ambas ciudades, nueve días para descubrir un Marruecos que no deja de transformarse." },
      { es: "Cruzarás el Alto Atlas, descubrirás Aït Ben Haddou y te adentrarás entre Boutaghrar, Amskar y las Gargantas del M'Goun, antes de continuar por el Valle del Dadès y las Gargantas del Todra." },
      { es: "Y entonces aparecerá el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer te esperan Merdani, Khamlia y Rissani." },
      { es: "Después, el Valle del Ziz, Ifrane y sus bosques de cedros marcarán el camino hacia Fez y su fascinante Medina." },
    ],
    closing: { es: "Nueve días entre ciudades imperiales, montañas, gargantas, oasis y dunas. Un viaje para dejarte sorprender por un Marruecos diferente detrás de cada horizonte." },
  },
  tourMarrakechFez910: {
    sourcePath: "/viajes/gransur/marrakech_fez/programa_9n_10d",
    paragraphs: [
      { es: "Imagina comenzar entre la energía y los colores de Marrakech… y terminar, diez días después, perdiéndote entre las callejuelas de Fez." },
      { es: "Entre ambas ciudades, Marruecos se transforma una y otra vez." },
      { es: "Cruzarás el Alto Atlas, descubrirás Aït Ben Haddou y te adentrarás entre Boutaghrar, Amskar, las Gargantas del M'Goun, el Valle del Dadès y Todra." },
      { es: "Después llegará el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol y dormirás bajo las estrellas. Y esta vez, el desierto se vive sin prisas: amanecer entre las dunas, Merdani, M'Fis, Khamlia y Rissani." },
      { es: "Finalmente, el Valle del Ziz, Ifrane y los bosques de cedros te conducirán hacia Fez." },
    ],
    closing: { es: "Diez días para atravesar Marruecos de sur a norte, dejando que cada montaña, cada duna y cada medina te descubran una nueva cara del país. Un viaje para vivir Marruecos, no solo para visitarlo." },
  },
  tourFezSidialiOzz56: {
    sourcePath: "/viajes/gransur/fez_sidiali_ozz/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas de Fez… y, solo unos días después, contemplar el atardecer desde las dunas del Sáhara." },
      { es: "Este viaje te llevará por algunos de los grandes contrastes de Marruecos." },
      { es: "Desde Fez cruzarás el Medio Atlas, entre Ifrane y bosques de cedros, hasta llegar al lago Aguelmame Sidi Ali. Después, el Parque Nacional de Khenifra y el inmenso palmeral del Valle del Ziz abrirán el camino hacia el desierto." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "El viaje continuará entre las Gargantas del Todra y el Valle del Dadès hasta alcanzar Ouarzazate." },
    ],
    closing: { es: "Seis días entre medinas, lagos, bosques, oasis, dunas y gargantas. Un viaje para descubrir cómo Marruecos puede cambiar por completo ante tus ojos en apenas unos kilómetros." },
  },
  tourFezSidialiOzz67: {
    sourcePath: "/viajes/gransur/fez_sidiali_ozz/programa_6n_7d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez, despertar junto a un lago en las montañas… y, unos días después, ver salir el sol sobre las dunas del Sáhara." },
      { es: "Durante siete días, Marruecos cambiará ante tus ojos." },
      { es: "Cruzarás el Medio Atlas, entre Ifrane y bosques de cedros, hasta llegar a Aguelmame Sidi Ali. El Parque Nacional de Khenifra y el Valle del Ziz te conducirán después hacia el desierto." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer, descubrirás Merdani, Khamlia y el mercado de Rissani." },
      { es: "Después, las dunas darán paso a las Gargantas del Todra y el Valle del Dadès, antes de alcanzar Ouarzazate." },
    ],
    closing: { es: "Siete días para pasar de la historia de Fez al silencio del Sáhara, entre lagos, bosques, oasis y montañas. Un viaje lleno de contrastes que invita a descubrir qué espera tras el próximo horizonte." },
  },
  tourFezSidialiOzz78: {
    sourcePath: "/viajes/gransur/fez_sidiali_ouarzazate/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre las callejuelas de Fez… y terminar ocho días después habiendo cruzado algunos de los paisajes más sorprendentes de Marruecos." },
      { es: "Desde la histórica Medina de Fez viajarás hacia el Medio Atlas, entre Ifrane y bosques de cedros, hasta alcanzar la serenidad de Aguelmame Sidi Ali." },
      { es: "Después, el Valle del Ziz abrirá el camino hacia el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol y pasarás una noche bajo las estrellas. Al amanecer te esperan Khamlia y Rissani." },
      { es: "El viaje continuará por las Gargantas del Todra y el Valle del Dadès, antes de adentrarte en el Alto Atlas Central, entre Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Y al final, Ouarzazate." },
    ],
    closing: { es: "Ocho días para descubrir un Marruecos de contrastes, donde cada etapa cambia el paisaje y convierte el camino en parte de la aventura." },
  },
  tourOzzSidialiFez56: {
    sourcePath: "/viajes/gransur/ozz_sidiali_fez/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar entre los paisajes de Ouarzazate… y terminar perdiéndote entre las callejuelas de la histórica Medina de Fez." },
      { es: "En solo seis días, este viaje te mostrará un Marruecos en constante transformación." },
      { es: "Descubrirás Aït Ben Haddou antes de adentrarte en el Valle del Dadès y las impresionantes Gargantas del Todra." },
      { es: "Después llegará el Sáhara." },
      { es: "En Erg Chebbi cambiarás el 4x4 por un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer, el camino continuará por Khamlia, Rissani y el inmenso palmeral del Valle del Ziz hasta alcanzar la tranquilidad de Aguelmame Sidi Ali." },
      { es: "Desde allí, los bosques de cedros e Ifrane te conducirán finalmente hasta Fez." },
    ],
    closing: { es: "Seis días entre kasbahs, gargantas, dunas, oasis, lagos y medinas. Un viaje para sentir cómo Marruecos cambia de paisaje a cada etapa." },
  },
  tourOzzSidialiFez67: {
    sourcePath: "/viajes/gransur/ozz_sidiali_fez/programa_6n_7d",
    paragraphs: [
      { es: "Imagina comenzar entre las kasbahs y los paisajes de Ouarzazate… y terminar, siete días después, en el corazón de la Medina de Fez." },
      { es: "Entre ambos lugares, Marruecos irá cambiando ante tus ojos." },
      { es: "Descubrirás Aït Ben Haddou, recorrerás el Valle del Dadès y caminarás entre las paredes de las Gargantas del Todra antes de alcanzar el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer te esperan Merdani, Khamlia y el mercado de Rissani." },
      { es: "Después, el inmenso palmeral del Valle del Ziz te llevará hacia Aguelmame Sidi Ali. Desde allí, los bosques de cedros e Ifrane marcarán el camino hasta Fez." },
    ],
    closing: { es: "Siete días entre kasbahs, gargantas, dunas, oasis, lagos y medinas. Un viaje para sentir cómo Marruecos se transforma a cada kilómetro." },
  },
  tourOzzSidialiFez78: {
    sourcePath: "/viajes/gransur/ozz_sidiali_fez/programa_7n_8d",
    paragraphs: [
      { es: "Imagina comenzar entre las kasbahs de Ouarzazate y terminar, ocho días después, perdiéndote entre las callejuelas de Fez." },
      { es: "Entre ambos lugares, te espera un Marruecos que cambia a cada paso." },
      { es: "Descubrirás Aït Ben Haddou y te adentrarás en el Alto Atlas Central, entre Boutaghrar, Amskar y las Gargantas del M'Goun. Después, el Valle del Dadès y las Gargantas del Todra abrirán el camino hacia el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "Al amanecer llegarán Khamlia y Rissani, antes de continuar por el Valle del Ziz hacia Aguelmame Sidi Ali." },
      { es: "Los bosques de cedros e Ifrane te conducirán finalmente hasta Fez." },
    ],
    closing: { es: "Ocho días entre kasbahs, montañas, dunas, oasis, lagos y medinas. Un viaje para atravesar Marruecos y descubrir un paisaje diferente detrás de cada horizonte." },
  },
  tourTangerRak89: {
    sourcePath: "/viajes/gransur/tanger-rak/programa_8n_9d",
    paragraphs: [
      { es: "Imagina comenzar donde el Atlántico se encuentra con el Mediterráneo… y terminar nueve días después entre los colores y la energía de Marrakech." },
      { es: "Este viaje es una auténtica travesía por Marruecos." },
      { es: "Desde Tánger llegarás al azul de Chefchaouen, para continuar entre Volubilis, Moulay Idriss, Meknes y la fascinante Medina de Fez." },
      { es: "Después, cruzarás el Medio Atlas y el Valle del Ziz hasta alcanzar el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol entre las dunas y pasarás una noche bajo las estrellas." },
      { es: "El camino seguirá por Khamlia, Rissani, las Gargantas del Todra y el Valle del Dadès." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka abrirán finalmente el camino hacia Marrakech." },
    ],
    closing: { es: "Nueve días para atravesar Marruecos de norte a sur, del azul de Chefchaouen al rojo de Marrakech, descubriendo un país que parece transformarse a cada horizonte." },
  },
  tourTangerRak910: {
    sourcePath: "/viajes/gransur/tanger-rak/programa_9n_10d",
    paragraphs: [
      { es: "Imagina comenzar donde el Atlántico se encuentra con el Mediterráneo… y terminar diez días después entre la energía y los colores de Marrakech." },
      { es: "En medio, todo un Marruecos por descubrir." },
      { es: "Desde Tánger llegarás al azul de Chefchaouen, antes de continuar por Volubilis, Moulay Idriss, Meknes y la fascinante Medina de Fez." },
      { es: "Cruzarás después el Medio Atlas y el Valle del Ziz hasta alcanzar el Sáhara." },
      { es: "En Erg Chebbi subirás a un dromedario, contemplarás la puesta de sol y dormirás bajo las estrellas." },
      { es: "Después llegarán Khamlia, Rissani, Todra y el Valle del Dadès, antes de adentrarte entre Boutaghrar, Amskar y las Gargantas del M'Goun." },
      { es: "Aït Ben Haddou y el Tizi n'Tichka abrirán finalmente el camino hacia Marrakech." },
    ],
    closing: { es: "Diez días del Mediterráneo al Sáhara, del azul de Chefchaouen al rojo de Marrakech. Un viaje para descubrir cuántos mundos diferentes caben dentro de Marruecos." },
  },
  tourCiudadesImperiales45: {
    sourcePath: "/viajes/norte/ciudades_imperiales/programa_4n_5d",
    paragraphs: [
      { es: "Imagina viajar a través de siglos de historia, recorriendo algunas de las ciudades que han dado forma a Marruecos." },
      { es: "El viaje comienza en Casablanca, frente al Atlántico y la imponente Mezquita Hassan II, antes de continuar hacia Rabat." },
      { es: "Desde allí descubrirás palacios, mausoleos y antiguas medinas, pero también viajarás mucho más atrás en el tiempo entre las ruinas romanas de Volubilis." },
      { es: "Moulay Idriss y Meknes te acercarán a otra cara de la historia del país, antes de llegar a Fez." },
      { es: "Y allí, el viaje parece detener el tiempo." },
      { es: "Te adentrarás a pie en Fez el-Bali, entre callejuelas medievales, zocos, talleres artesanales, escuelas coránicas y las tradicionales tenerías." },
    ],
    closing: { es: "Cinco días para viajar por la memoria de Marruecos. De Casablanca a Fez, una ruta entre ciudades imperiales, monumentos y medinas donde siglos de historia continúan formando parte de la vida cotidiana." },
  },
  tourCiudadesImperiales67: {
    sourcePath: "/viajes/norte/ciudades_imperiales/programa_6n_7d",
    paragraphs: [
      { es: "Imagina recorrer Marruecos siguiendo las huellas de sus grandes ciudades históricas… desde el Atlántico hasta la energía de Marrakech." },
      { es: "El viaje comienza en Casablanca, frente a la Mezquita Hassan II, antes de continuar hacia Rabat, Volubilis, Moulay Idriss y Meknes." },
      { es: "Después llegará Fez." },
      { es: "Te perderás a pie entre las callejuelas de Fez el-Bali, sus zocos, talleres artesanales, escuelas coránicas y tenerías tradicionales." },
      { es: "Pero el viaje todavía guarda otro cambio de escenario." },
      { es: "Cruzarás el Medio Atlas pasando por Ifrane, bosques de cedros, Khenifra y Beni Mellal hasta alcanzar Marrakech." },
      { es: "Allí te esperan la Koutoubia, el Palacio de la Bahía, los artesanos de los zocos y la inconfundible Djemaa el-Fna." },
    ],
    closing: { es: "Siete días para viajar por la historia, la cultura y los paisajes de Marruecos. De Casablanca a Marrakech, un recorrido donde cada ciudad revela una forma diferente de sentir el país." },
  },
  tourCiudadesImperialesRif67: {
    sourcePath: "/viajes/norte/ciudadesimperiales_rif/programa_6n_7d",
    paragraphs: [
      { es: "Imagina comenzar donde el Atlántico y el Mediterráneo se encuentran… y terminar siete días después entre los colores y la energía de Marrakech." },
      { es: "Este viaje te llevará por un Marruecos lleno de contrastes." },
      { es: "Desde Tánger descubrirás Cabo Espartel y Tetuán, antes de adentrarte en las montañas del Rif y llegar a las inconfundibles callejuelas azules de Chefchaouen." },
      { es: "Después, viajarás entre siglos de historia: las ruinas romanas de Volubilis, Moulay Idriss, Meknes y la fascinante medina de Fez." },
      { es: "Desde allí, el paisaje volverá a cambiar." },
      { es: "Cruzarás el Medio Atlas, pasando por Ifrane, bosques de cedros, Khenifra y Beni Mellal hasta llegar a Marrakech." },
      { es: "Te esperan la Koutoubia, el Palacio de la Bahía, los zocos y Jemaa el-Fna." },
    ],
    closing: { es: "Siete días del azul del Rif al rojo de Marrakech. Un viaje para descubrir la historia, los paisajes y las ciudades que hacen de Marruecos un país imposible de resumir en una sola imagen." },
  },
  tourCiudadesImperialesRif78: {
    sourcePath: "/viajes/norte/ciudadesimperiales_rif/programa_7n_8d",
    paragraphs: [
      { es: "Audioguía · Ciudades Imperiales y el Rif · 8 días" },
      { es: "Imagina comenzar donde el Atlántico y el Mediterráneo se encuentran… y terminar ocho días después en el corazón de Marrakech." },
      { es: "Este viaje es una travesía por los colores, la historia y los paisajes de Marruecos." },
      { es: "Desde Tánger llegarás a Tetuán y después a las montañas del Rif, donde te esperan las inconfundibles callejuelas azules de Chefchaouen." },
      { es: "El camino continuará hacia Rabat, antes de viajar entre siglos de historia por Volubilis, Moulay Idriss, Meknes y la fascinante medina de Fez." },
      { es: "Después, el paisaje se transforma." },
      { es: "Atravesarás el Medio Atlas, pasando por Ifrane, bosques de cedros, Khenifra y Beni Mellal, hasta alcanzar Marrakech." },
      { es: "Allí descubrirás la Koutoubia, el Palacio de la Bahía, los zocos y Jemaa el-Fna." },
    ],
    closing: { es: "Ocho días del azul del Rif al rojo de Marrakech. Un viaje para recorrer Marruecos de norte a sur y descubrir cómo cada ciudad, cada medina y cada paisaje cuentan una historia diferente." },
  },
  tourTangerFez45: {
    sourcePath: "/viajes/norte/tanger_fez/programa_4n_5d",
    paragraphs: [
      { es: "Imagina comenzar tu viaje allí donde el Atlántico y el Mediterráneo se encuentran… y terminar, cinco días después, perdiéndote entre las callejuelas de Fez." },
      { es: "Desde Tánger, Cabo Espartel y las Grutas de Hércules marcarán el inicio del camino hacia Tetuán y su medina." },
      { es: "Después llegarán las montañas del Rif, las cascadas de Akchour y uno de los lugares más especiales del viaje: Chefchaouen, con sus plazas y sus inconfundibles callejuelas azules." },
      { es: "El recorrido continuará entre siglos de historia, desde las ruinas romanas de Volubilis hasta Moulay Idriss y la ciudad imperial de Meknes." },
      { es: "Y al final, Fez." },
      { es: "Una ciudad para descubrir a pie, entre zocos, talleres artesanales, escuelas coránicas y tenerías tradicionales." },
    ],
    closing: { es: "Cinco días entre mar, montañas, ciudades azules y medinas. Una escapada para descubrir cuánto Marruecos puede caber en un solo viaje." },
  },
  tourTangerFez56: {
    sourcePath: "/viajes/norte/tanger_fez/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar allí donde el Atlántico y el Mediterráneo se encuentran… y terminar seis días después en el corazón de la histórica Fez." },
      { es: "Desde Tánger, Cabo Espartel y las Grutas de Hércules abrirán el camino hacia Asilah, con sus calles blancas, murales y murallas frente al Atlántico." },
      { es: "Después llegará Tetuán, antes de adentrarte entre las montañas del Rif y las cascadas de Akchour hasta alcanzar las inconfundibles callejuelas azules de Chefchaouen." },
      { es: "El viaje continuará entre siglos de historia: las ruinas romanas de Volubilis, Moulay Idriss y la ciudad imperial de Meknes." },
      { es: "Y finalmente, Fez." },
      { es: "Una ciudad para descubrir a pie, entre callejuelas medievales, zocos, talleres artesanales, escuelas coránicas y tenerías tradicionales." },
    ],
    closing: { es: "Seis días entre dos mares, ciudades blancas y azules, montañas y medinas. Un viaje por el norte de Marruecos donde cada etapa parece cambiar por completo el escenario." },
  },
  tourFezTanger56: {
    sourcePath: "/viajes/norte/fez_tanger/programa_5n_6d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas medievales de Fez… y terminar seis días después frente al lugar donde el Atlántico y el Mediterráneo se encuentran." },
      { es: "Este viaje recorre el norte de Marruecos entre historia, montañas y mar." },
      { es: "Descubrirás Fez el-Bali a pie, entre zocos, talleres artesanales y tenerías tradicionales, antes de continuar hacia Meknes, las ruinas romanas de Volubilis y Moulay Idriss." },
      { es: "Después, el paisaje cambiará con la llegada al Rif y a las inconfundibles calles azules de Chefchaouen." },
      { es: "Las cascadas de Akchour abrirán el camino hacia Tetuán y su medina de herencia andalusí." },
      { es: "Y finalmente, Tánger, pasando antes por las Grutas de Hércules y Cabo Espartel." },
    ],
    closing: { es: "Seis días para viajar desde el corazón histórico de Marruecos hasta el mar, entre medinas, ruinas romanas, montañas y ciudades azules. Un viaje donde cada etapa te acerca a una nueva cara del norte." },
  },
  tourFezTanger67: {
    sourcePath: "/viajes/norte/fez_tanger/programa_6n_7d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas medievales de Fez… y terminar siete días después frente al encuentro del Atlántico y el Mediterráneo." },
      { es: "El viaje comienza entre zocos, talleres artesanales y tenerías tradicionales, antes de continuar hacia Meknes, las ruinas romanas de Volubilis y Moulay Idriss." },
      { es: "Después aparecerán las montañas del Rif y las inconfundibles calles azules de Chefchaouen." },
      { es: "Las cascadas de Akchour te acompañarán en el camino hacia Tetuán y su medina de herencia andalusí." },
      { es: "Y entonces llegará el Atlántico." },
      { es: "En Asilah descubrirás calles blancas, murales artísticos y antiguas murallas portuguesas frente al océano." },
      { es: "El viaje culminará entre las Grutas de Hércules, Cabo Espartel y Tánger." },
    ],
    closing: { es: "Siete días para viajar de las medinas al mar, entre historia, montañas y ciudades llenas de color. Un recorrido por el norte de Marruecos que cambia de escenario a cada etapa." },
  },
  tourEnduroAventura45: {
    sourcePath: "/viajes/aventura/enduro/programa_4n_5d",
    paragraphs: [
      { es: "Imagina arrancar el motor y tener ante ti kilómetros de desierto, pistas abiertas y dunas esperando ser recorridas." },
      { es: "Durante cinco días, el Sáhara se convierte en el escenario de una auténtica aventura sobre una moto de enduro." },
      { es: "Desde Erfoud comenzarás a rodar entre pistas desérticas, ríos de arena y oasis, acercándote a las grandes dunas de Erg Chebbi y aprendiendo a dominar la conducción sobre arena." },
      { es: "La ruta continuará por los Pozos de Jorf, Rissani y paisajes abiertos antes de alcanzar el desierto para pasar una noche en un bivouac, bajo las estrellas." },
      { es: "Y todavía quedará una auténtica jornada dakariana: dunas, oasis escondidos, Merzouga y su chott antes de regresar a Erfoud." },
    ],
    closing: { es: "Cinco días de arena, motor y aventura. Una experiencia para quienes no quieren limitarse a contemplar el Sáhara, sino que sueñan con recorrerlo sobre dos ruedas." },
  },
  tourEnduroAventura67: {
    sourcePath: "/viajes/aventura/enduro/programa_6n_7d",
    paragraphs: [
      { es: "Imagina arrancar el motor en Erfoud y saber que, durante los próximos días, el camino serán pistas abiertas, montañas, arena y horizontes que parecen no terminar nunca." },
      { es: "Esta es una aventura para vivir Marruecos sobre dos ruedas." },
      { es: "Pilotarás por el Kemkem hasta Alnif, antes de adentrarte en las pistas del Saghro y alcanzar Boumalne Dades." },
      { es: "Después llegará el Alto Atlas Central, entre gargantas, ríos, ramblas pedregosas y pequeños pueblos bereberes." },
      { es: "La ruta continuará cruzando el Anti Atlas hasta Zagora." },
      { es: "Y entonces llegará una gran jornada de desierto: el plateau de Rekam, Lac Maider, Oued Remlia, Ouzina y las pistas de arena que conducen hasta Merzouga y Erfoud." },
    ],
    closing: { es: "Siete días de pilotaje, montaña, desierto y aventura. Una travesía para quienes quieren sentir Marruecos desde el manillar y descubrir qué se esconde al final de cada pista." },
  },
  tourEscapadaDesierto34: {
    sourcePath: "/viajes/escapadas/desierto/programa_3n_4d",
    paragraphs: [
      { es: "Imagina escapar durante unos días a un lugar donde el horizonte parece infinito y el tiempo comienza a avanzar a otro ritmo." },
      { es: "Desde Erfoud te adentrarás en el Sáhara, recorriendo antiguas pistas del Rally Dakar, poblados y paisajes desérticos hasta alcanzar el gran Erg Chebbi." },
      { es: "Allí dejarás atrás el 4x4 para subir a un dromedario y avanzar lentamente entre las dunas mientras el sol se pone sobre el desierto." },
      { es: "Después llegará una de esas noches difíciles de olvidar: dormir en un bivouac, bajo un cielo lleno de estrellas." },
      { es: "Al amanecer, el viaje continuará por Merdani, Khamlia y Rissani, antes de despedirte del sur contemplando el Valle del Ziz." },
    ],
    closing: { es: "Cuatro días para cambiar el ruido por el silencio, las prisas por el ritmo del desierto y la rutina por una experiencia que puede quedarse contigo mucho más tiempo que el propio viaje." },
  },
  tourEscapadaAtlas34: {
    sourcePath: "/viajes/escapadas/atlas/programa_3n_4d",
    paragraphs: [
      { es: "Imagina dejar atrás la rutina y adentrarte, en apenas cuatro días, en un Marruecos de montañas, valles y pequeñas aldeas donde la vida conserva otro ritmo." },
      { es: "Desde Ouarzazate viajarás hacia Boumalne Dadès para descubrir el corazón del Alto Atlas Central." },
      { es: "En 4x4 recorrerás pistas entre Boutaghrar y Amskar, atravesando valles y cañones hasta las Gargantas del M'Goun. En el camino conocerás poblados Imazighen y descubrirás las grutas donde todavía habitan familias nómadas." },
      { es: "Después, el paisaje volverá a transformarse." },
      { es: "Atravesarás el Anti-Atlas y las formaciones del Djebel Saghro hasta N'Kob, antes de continuar entre kasbahs y palmerales por el Valle del Drâa hacia Ouarzazate." },
    ],
    closing: { es: "Cuatro días para desconectar y acercarte a otro Marruecos: el de las montañas, las aldeas y los grandes paisajes del Atlas. Una escapada breve, pero llena de encuentros y contrastes." },
  },
  tourEscapadaFez23: {
    sourcePath: "/viajes/escapadas/fez/programa_2n_3d",
    paragraphs: [
      { es: "Imagina cruzar una puerta y sentir que, de repente, el ritmo del mundo cambia." },
      { es: "Eso es Fez." },
      { es: "Durante tres días te adentrarás a pie en Fez-el Bali, recorriendo un laberinto de callejuelas medievales donde cada giro puede descubrirte un zoco, un taller artesanal, una mezquita, un palacio o una escuela coránica." },
      { es: "Conocerás las tradicionales tenerías de Chouara y descubrirás cómo se organiza la vida en los antiguos barrios de la medina, entre fuentes, hornos, hammams y espacios de encuentro." },
      { es: "Y al final del día, subirás hasta un mirador para contemplar Fez mientras la última llamada a la oración se extiende sobre la ciudad." },
    ],
    closing: { es: "Tres días para caminar sin prisas, dejarte llevar por la medina y sumergirte en siglos de historia, artesanía y tradición. Una escapada para no limitarte a visitar Fez, sino sentirla." },
  },
  tourEscapadaFez34: {
    sourcePath: "/viajes/escapadas/fez/programa_3n_4d",
    paragraphs: [
      { es: "Imagina perderte entre callejuelas medievales, escuchar el trabajo de los artesanos y sentir que, por unos días, has viajado a otro tiempo." },
      { es: "Fez será el corazón de esta escapada." },
      { es: "Recorrerás a pie Fez-el Bali, entre zocos, talleres, madrazas, palacios y las históricas tenerías de Chouara, descubriendo una medina donde la vida sigue latiendo entre siglos de historia." },
      { es: "Pero el viaje continúa más allá de sus murallas." },
      { es: "Conocerás Meknès y su legado imperial, caminarás entre las ruinas romanas de Volubilis y llegarás hasta Moulay Idriss antes de regresar a Fez." },
    ],
    closing: { es: "Cuatro días para dejarte llevar por la historia de Marruecos, desde el laberinto de una medina hasta ciudades imperiales y antiguas ruinas. Una escapada para caminar, observar y sentir que el pasado todavía forma parte del presente." },
  },
  tourEscapadaFezSidiali34: {
    sourcePath: "/viajes/escapadas/fez_sidiali/programa_3n_4d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas medievales de Fez… y terminar despertando frente a un lago, rodeado por las montañas del Medio Atlas." },
      { es: "En Fez te adentrarás a pie en Fez-el Bali, entre zocos, talleres artesanales, palacios y las históricas tenerías, descubriendo una medina donde siglos de historia siguen formando parte de la vida cotidiana." },
      { es: "Después, el paisaje cambiará por completo." },
      { es: "Dejarás atrás la ciudad para viajar hacia Ifrane y atravesar los bosques de cedros del Medio Atlas hasta alcanzar Aguelmame Sidi Ali." },
      { es: "Allí te espera un entorno de montaña para caminar junto al lago, descansar y disfrutar de la naturaleza antes del regreso." },
    ],
    closing: { es: "Cuatro días para pasar del laberinto de una antigua medina al silencio de las montañas. Una escapada que combina cultura y naturaleza y descubre dos caras completamente diferentes de Marruecos." },
  },
  tourEscapadaFezSidiali45: {
    sourcePath: "/viajes/escapadas/fez_sidiali/programa_4n_5d",
    paragraphs: [
      { es: "Imagina comenzar perdiéndote entre las callejuelas medievales de Fez… y terminar despertando frente a un lago, rodeado por las montañas del Medio Atlas." },
      { es: "Durante cinco días descubrirás un Marruecos lleno de contrastes." },
      { es: "Caminarás por Fez-el Bali entre zocos, talleres artesanales y las históricas tenerías de Chouara." },
      { es: "Después viajarás hasta Meknès, recorrerás las ruinas romanas de Volubilis y descubrirás Moulay Idriss antes de regresar a Fez." },
      { es: "Y cuando creas haber conocido el corazón histórico del viaje, el paisaje cambiará por completo." },
      { es: "Ifrane y los bosques de cedros abrirán el camino hacia Aguelmame Sidi Ali, donde podrás disfrutar de la tranquilidad del lago y su entorno de montaña." },
    ],
    closing: { es: "Cinco días para viajar entre medinas, ciudades imperiales, ruinas y naturaleza. Una escapada que comienza entre siglos de historia y termina en el silencio del Medio Atlas." },
  },
  tourEscapadaMarrakech23: {
    sourcePath: "/viajes/escapadas/marrakech/programa_2n_3d",
    paragraphs: [
      { es: "Imagina llegar a una ciudad que no se limita a enseñarse… sino que se escucha, se huele y se siente desde el primer momento." },
      { es: "Bienvenido a Marrakech." },
      { es: "Durante tres días te adentrarás en el corazón de su Medina, entre callejuelas, artesanos, aromas y el movimiento constante de los zocos." },
      { es: "Descubrirás la Koutoubia y el Palacio de la Bahía antes de dejarte llevar nuevamente hasta Djemaa el-Fna." },
      { es: "Una plaza que cambia por completo cuando cae el sol y las luces, los puestos de comida y sus personajes transforman el espacio en un gran escenario al aire libre." },
      { es: "Y todavía tendrás tiempo para volver a perderte por la Medina a tu propio ritmo." },
    ],
    closing: { es: "Tres días para cambiar de escenario, dejarte llevar por los sentidos y descubrir por qué Marrakech se vive con tanta intensidad. Una escapada corta para sentir que has viajado mucho más lejos." },
  },
  tourEscapadaRakAgafay34: {
    sourcePath: "/viajes/escapadas/marrakech_agafay/programa_3n_4d",
    paragraphs: [
      { es: "Imagina comenzar entre el bullicio, los aromas y los colores de Marrakech… y terminar contemplando las estrellas en el silencio de Agafay." },
      { es: "Durante cuatro días vivirás dos caras completamente diferentes de Marruecos." },
      { es: "Primero te adentrarás en la Medina de Marrakech, entre Djemaa el-Fna, la Koutoubia, el Palacio de la Bahía, los zocos y sus talleres artesanales." },
      { es: "Después dejarás atrás la ciudad." },
      { es: "Cruzarás la Meseta del Kik y pasarás junto al lago Lalla Takerkoust antes de alcanzar los paisajes áridos de Agafay, a los pies del Alto Atlas." },
      { es: "Allí subirás a un dromedario para contemplar la puesta de sol y pasarás la noche en un bivouac bajo las estrellas." },
    ],
    closing: { es: "Cuatro días para pasar de la intensidad de Marrakech al silencio del desierto. Una escapada de contrastes para sentir que, en muy poco tiempo, has vivido dos viajes completamente diferentes." },
  },
};

export const journeyPostcardFor = (routeId) => JOURNEY_POSTCARDS[routeId] || null;
