/* ============================================================
   juegoData.js — dataset for the /juego interactive explorer
   ------------------------------------------------------------
   Trilingual catalogue of selectable Moroccan places. Each entry
   carries a representative image + short description so the game
   doubles as an educational, exploratory experience. User progress
   lives in localStorage on the client.
============================================================ */

const T = (es, en, fr) => ({ es, en, fr });

/* Region ids shared with the region map (north, imperial, coast,
   atlas, sahara, south). Used for "regiones completadas". */
export const REGION_LABELS = {
  north: T("Norte de Marruecos", "Northern Morocco", "Nord du Maroc"),
  imperial: T("Ciudades Imperiales", "Imperial Cities", "Cités Impériales"),
  coast: T("Costa Atlántica", "Atlantic Coast", "Côte Atlantique"),
  atlas: T("Atlas y valles", "Atlas & valleys", "Atlas & vallées"),
  sahara: T("Desierto del Sáhara", "Sahara Desert", "Désert du Sahara"),
  south: T("Sur de Marruecos", "Southern Morocco", "Sud du Maroc"),
};

export const REGION_ORDER = ["north", "imperial", "coast", "atlas", "sahara", "south"];

/* Categories — order defines the on-page section order. */
export const CATEGORIES = [
  { id: "regions", icon: "Map", name: T("Regiones", "Regions", "Régions") },
  { id: "cities", icon: "Building2", name: T("Ciudades", "Cities", "Villes") },
  { id: "villages", icon: "Castle", name: T("Pueblos y Kasbahs", "Villages & Kasbahs", "Villages & Kasbahs") },
  { id: "deserts", icon: "Sun", name: T("Desiertos", "Deserts", "Déserts") },
  { id: "mountains", icon: "Mountain", name: T("Montañas y Valles", "Mountains & Valleys", "Montagnes & Vallées") },
  { id: "beaches", icon: "Waves", name: T("Playas y Costa", "Beaches & Coast", "Plages & Côte") },
  { id: "monuments", icon: "Landmark", name: T("Monumentos e Historia", "Monuments & History", "Monuments & Histoire") },
  { id: "attractions", icon: "Camera", name: T("Atracciones Turísticas", "Tourist Attractions", "Attractions Touristiques") },
  { id: "experiences", icon: "Sparkles", name: T("Experiencias Clave", "Key Experiences", "Expériences Clés") },
];

const IMG = {
  "rg-north": "https://images.pexels.com/photos/33900140/pexels-photo-33900140.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "rg-imperial": "https://images.pexels.com/photos/36782884/pexels-photo-36782884.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "rg-coast": "https://images.pexels.com/photos/37138819/pexels-photo-37138819.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "rg-atlas": "https://images.pexels.com/photos/37714712/pexels-photo-37714712.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "rg-sahara": "https://images.pexels.com/photos/30710172/pexels-photo-30710172.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "rg-south": "https://images.pexels.com/photos/33514521/pexels-photo-33514521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-marrakech": "https://images.pexels.com/photos/17649841/pexels-photo-17649841.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-fez": "https://images.pexels.com/photos/36782884/pexels-photo-36782884.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-meknes": "https://images.pexels.com/photos/6545522/pexels-photo-6545522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-rabat": "https://images.pexels.com/photos/19084081/pexels-photo-19084081.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-casablanca": "https://images.pexels.com/photos/20657116/pexels-photo-20657116.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-tanger": "https://images.pexels.com/photos/10205137/pexels-photo-10205137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-chefchaouen": "https://images.pexels.com/photos/33900140/pexels-photo-33900140.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-tetuan": "https://images.pexels.com/photos/11660299/pexels-photo-11660299.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-ouarzazate": "https://images.pexels.com/photos/23456866/pexels-photo-23456866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-agadir": "https://images.pexels.com/photos/30557503/pexels-photo-30557503.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-essaouira": "https://images.pexels.com/photos/35846256/pexels-photo-35846256.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ci-merzouga": "https://images.pexels.com/photos/19190939/pexels-photo-19190939.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-aitbenhaddou": "https://images.pexels.com/photos/33514521/pexels-photo-33514521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-imlil": "https://images.pexels.com/photos/35449656/pexels-photo-35449656.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-tinghir": "https://images.pexels.com/photos/37441764/pexels-photo-37441764.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-skoura": "https://images.pexels.com/photos/6768980/pexels-photo-6768980.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-boumalne": "https://images.pexels.com/photos/28804535/pexels-photo-28804535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-moulayidriss": "https://images.pexels.com/photos/11105418/pexels-photo-11105418.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-asilah": "https://images.pexels.com/photos/30699171/pexels-photo-30699171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "vk-telouet": "https://images.pexels.com/photos/37684084/pexels-photo-37684084.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "de-ergchebbi": "https://images.pexels.com/photos/4805548/pexels-photo-4805548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "de-ergchigaga": "https://images.pexels.com/photos/10790260/pexels-photo-10790260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "de-agafay": "https://images.pexels.com/photos/15258884/pexels-photo-15258884.png?auto=compress&cs=tinysrgb&h=650&w=940",
  "de-zagora": "https://images.pexels.com/photos/11387352/pexels-photo-11387352.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "de-draa": "https://images.pexels.com/photos/17399234/pexels-photo-17399234.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-toubkal": "https://images.pexels.com/photos/37538525/pexels-photo-37538525.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-dades": "https://images.pexels.com/photos/14145715/pexels-photo-14145715.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-todra": "https://images.pexels.com/photos/34728488/pexels-photo-34728488.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-ourika": "https://images.pexels.com/photos/28200419/pexels-photo-28200419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-draavalley": "https://images.pexels.com/photos/17399234/pexels-photo-17399234.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-mgoun": "https://images.pexels.com/photos/37401857/pexels-photo-37401857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-ifrane": "https://images.pexels.com/photos/30797697/pexels-photo-30797697.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mo-rif": "https://images.pexels.com/photos/35192333/pexels-photo-35192333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "be-essaouira": "https://images.pexels.com/photos/36606715/pexels-photo-36606715.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "be-agadir": "https://images.pexels.com/photos/30557503/pexels-photo-30557503.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "be-legzira": "https://images.pexels.com/photos/28901142/pexels-photo-28901142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "be-taghazout": "https://images.pexels.com/photos/37055613/pexels-photo-37055613.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "be-saidia": "https://images.pexels.com/photos/13773632/pexels-photo-13773632.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "be-dakhla": "https://images.pexels.com/photos/30143183/pexels-photo-30143183.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-volubilis": "https://images.pexels.com/photos/18767562/pexels-photo-18767562.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-koutoubia": "https://images.pexels.com/photos/14412355/pexels-photo-14412355.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-feselbali": "https://images.pexels.com/photos/35097550/pexels-photo-35097550.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-saadies": "https://images.pexels.com/photos/36202817/pexels-photo-36202817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-bahia": "https://images.pexels.com/photos/10306569/pexels-photo-10306569.png?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-babmansour": "https://images.pexels.com/photos/37347995/pexels-photo-37347995.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-bouinania": "https://images.pexels.com/photos/31221481/pexels-photo-31221481.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "mn-skala": "https://images.pexels.com/photos/13998072/pexels-photo-13998072.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-jemaaelfna": "https://images.pexels.com/photos/35028438/pexels-photo-35028438.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-majorelle": "https://images.pexels.com/photos/5435195/pexels-photo-5435195.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-zocos": "https://images.pexels.com/photos/30124130/pexels-photo-30124130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-curtidurias": "https://images.pexels.com/photos/17042434/pexels-photo-17042434.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-ouzoud": "https://images.pexels.com/photos/35669894/pexels-photo-35669894.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-hercules": "https://images.pexels.com/photos/1722206/pexels-photo-1722206.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-atlasstudios": "https://images.pexels.com/photos/19281432/pexels-photo-19281432.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "at-dayetaoua": "https://images.pexels.com/photos/37700635/pexels-photo-37700635.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-bivouac": "https://images.pexels.com/photos/35666328/pexels-photo-35666328.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-camel": "https://images.pexels.com/photos/29184041/pexels-photo-29184041.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-medina": "https://images.pexels.com/photos/2610815/pexels-photo-2610815.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-4x4": "https://images.pexels.com/photos/30330000/pexels-photo-30330000.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-oasis": "https://images.pexels.com/photos/36955390/pexels-photo-36955390.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-berbertea": "https://images.pexels.com/photos/30497987/pexels-photo-30497987.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-sunrise": "https://images.pexels.com/photos/30099211/pexels-photo-30099211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-hammam": "https://images.pexels.com/photos/33279021/pexels-photo-33279021.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-trek": "https://images.pexels.com/photos/37401852/pexels-photo-37401852.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-cooking": "https://images.pexels.com/photos/37254183/pexels-photo-37254183.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-surf": "https://images.pexels.com/photos/36005570/pexels-photo-36005570.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
  "ex-sandboard": "https://images.pexels.com/photos/17112748/pexels-photo-17112748.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
};

/* The full catalogue. Each place: id, cat, region, name, desc, image, optional coords. */
export const PLACES = [
  // ---- Regiones (macro) ----
  { id: "rg-north", cat: "regions", region: "north", coords: [35.17, -5.27], image: IMG["rg-north"],
    name: REGION_LABELS.north,
    desc: T("Montañas del Rif, el Mediterráneo y la célebre medina azul de Chefchaouen.", "Rif mountains, the Mediterranean and the famous blue medina of Chefchaouen.", "Montagnes du Rif, la Méditerranée et la célèbre médina bleue de Chefchaouen.") },
  { id: "rg-imperial", cat: "regions", region: "imperial", coords: [34.03, -5.0], image: IMG["rg-imperial"],
    name: REGION_LABELS.imperial,
    desc: T("Las cuatro ciudades imperiales: mil años de historia, palacios y artesanía.", "The four imperial cities: a thousand years of history, palaces and craft.", "Les quatre cités impériales : mille ans d'histoire, palais et artisanat.") },
  { id: "rg-coast", cat: "regions", region: "coast", coords: [31.51, -9.77], image: IMG["rg-coast"],
    name: REGION_LABELS.coast,
    desc: T("Playas atlánticas, vientos alisios y la luz dorada de Essaouira.", "Atlantic beaches, trade winds and the golden light of Essaouira.", "Plages atlantiques, alizés et la lumière dorée d'Essaouira.") },
  { id: "rg-atlas", cat: "regions", region: "atlas", coords: [31.3, -7.6], image: IMG["rg-atlas"],
    name: REGION_LABELS.atlas,
    desc: T("Cumbres bereberes, valles verdes y aldeas de adobe del Alto Atlas.", "Berber peaks, green valleys and adobe villages of the High Atlas.", "Sommets berbères, vallées verdoyantes et villages d'adobe du Haut Atlas.") },
  { id: "rg-sahara", cat: "regions", region: "sahara", coords: [31.1, -4.0], image: IMG["rg-sahara"],
    name: REGION_LABELS.sahara,
    desc: T("El gran desierto: dunas doradas, noches estrelladas y caravanas.", "The great desert: golden dunes, starry nights and caravans.", "Le grand désert : dunes dorées, nuits étoilées et caravanes.") },
  { id: "rg-south", cat: "regions", region: "south", coords: [30.42, -6.9], image: IMG["rg-south"],
    name: REGION_LABELS.south,
    desc: T("Kasbahs de barro, oasis y el cinematográfico valle del Drâa.", "Mud kasbahs, oases and the cinematic Drâa valley.", "Kasbahs de terre, oasis et la cinématographique vallée du Drâa.") },

  // ---- Ciudades ----
  { id: "ci-marrakech", cat: "cities", region: "imperial", coords: [31.63, -7.99], image: IMG["ci-marrakech"],
    name: T("Marrakech", "Marrakech", "Marrakech"),
    desc: T("La ciudad roja: zocos, jardines y la vibrante plaza Jemaa el-Fna.", "The red city: souks, gardens and the vibrant Jemaa el-Fna square.", "La ville rouge : souks, jardins et la place animée Jemaa el-Fna.") },
  { id: "ci-fez", cat: "cities", region: "imperial", coords: [34.03, -5.0], image: IMG["ci-fez"],
    name: T("Fez", "Fez", "Fès"),
    desc: T("Capital espiritual y la medina medieval más grande del mundo.", "Spiritual capital and the world's largest medieval medina.", "Capitale spirituelle et la plus grande médina médiévale du monde.") },
  { id: "ci-meknes", cat: "cities", region: "imperial", coords: [33.89, -5.55], image: IMG["ci-meknes"],
    name: T("Meknès", "Meknes", "Meknès"),
    desc: T("Ciudad imperial amurallada, célebre por la monumental Bab Mansour.", "Walled imperial city, famous for the monumental Bab Mansour.", "Cité impériale fortifiée, célèbre pour la monumentale Bab Mansour.") },
  { id: "ci-rabat", cat: "cities", region: "imperial", coords: [34.02, -6.83], image: IMG["ci-rabat"],
    name: T("Rabat", "Rabat", "Rabat"),
    desc: T("La capital: kasbah de los Oudayas, torre Hassan y aire atlántico.", "The capital: Oudayas kasbah, Hassan Tower and Atlantic air.", "La capitale : kasbah des Oudayas, tour Hassan et air atlantique.") },
  { id: "ci-casablanca", cat: "cities", region: "coast", coords: [33.57, -7.59], image: IMG["ci-casablanca"],
    name: T("Casablanca", "Casablanca", "Casablanca"),
    desc: T("Metrópolis moderna frente a la imponente mezquita Hassan II.", "Modern metropolis facing the imposing Hassan II Mosque.", "Métropole moderne face à l'imposante mosquée Hassan II.") },
  { id: "ci-tanger", cat: "cities", region: "north", coords: [35.76, -5.83], image: IMG["ci-tanger"],
    name: T("Tánger", "Tangier", "Tanger"),
    desc: T("Puerta entre dos continentes, cosmopolita y literaria.", "Gateway between two continents, cosmopolitan and literary.", "Porte entre deux continents, cosmopolite et littéraire.") },
  { id: "ci-chefchaouen", cat: "cities", region: "north", coords: [35.17, -5.26], image: IMG["ci-chefchaouen"],
    name: T("Chefchaouen", "Chefchaouen", "Chefchaouen"),
    desc: T("La perla azul del Rif, un laberinto de callejones índigo.", "The blue pearl of the Rif, a maze of indigo alleys.", "La perle bleue du Rif, un dédale de ruelles indigo.") },
  { id: "ci-tetuan", cat: "cities", region: "north", coords: [35.57, -5.37], image: IMG["ci-tetuan"],
    name: T("Tetuán", "Tetouan", "Tétouan"),
    desc: T("Medina blanca de herencia andalusí, Patrimonio de la Humanidad.", "White medina of Andalusian heritage, a World Heritage site.", "Médina blanche d'héritage andalou, patrimoine mondial.") },
  { id: "ci-ouarzazate", cat: "cities", region: "south", coords: [30.92, -6.91], image: IMG["ci-ouarzazate"],
    name: T("Ouarzazate", "Ouarzazate", "Ouarzazate"),
    desc: T("La puerta del desierto y capital del cine marroquí.", "The gateway to the desert and capital of Moroccan cinema.", "La porte du désert et capitale du cinéma marocain.") },
  { id: "ci-agadir", cat: "cities", region: "coast", coords: [30.42, -9.6], image: IMG["ci-agadir"],
    name: T("Agadir", "Agadir", "Agadir"),
    desc: T("Balneario atlántico de grandes playas y sol todo el año.", "Atlantic resort of wide beaches and year-round sun.", "Station atlantique aux grandes plages et soleil toute l'année.") },
  { id: "ci-essaouira", cat: "cities", region: "coast", coords: [31.51, -9.76], image: IMG["ci-essaouira"],
    name: T("Essaouira", "Essaouira", "Essaouira"),
    desc: T("Ciudad fortificada del viento, puerto azul y música gnawa.", "Fortified city of wind, blue port and Gnawa music.", "Cité fortifiée du vent, port bleu et musique gnaoua.") },
  { id: "ci-merzouga", cat: "cities", region: "sahara", coords: [31.1, -3.98], image: IMG["ci-merzouga"],
    name: T("Merzouga", "Merzouga", "Merzouga"),
    desc: T("Pueblo a las puertas de las dunas del Erg Chebbi.", "Village at the gates of the Erg Chebbi dunes.", "Village aux portes des dunes de l'Erg Chebbi.") },

  // ---- Pueblos y Kasbahs ----
  { id: "vk-aitbenhaddou", cat: "villages", region: "south", coords: [31.05, -7.13], image: IMG["vk-aitbenhaddou"],
    name: T("Aït Ben Haddou", "Aït Ben Haddou", "Aït Ben Haddou"),
    desc: T("Ksar de adobe Patrimonio de la Humanidad, escenario de cine.", "Adobe ksar, a World Heritage site and film location.", "Ksar en adobe, patrimoine mondial et décor de cinéma.") },
  { id: "vk-imlil", cat: "villages", region: "atlas", coords: [31.14, -7.92], image: IMG["vk-imlil"],
    name: T("Imlil", "Imlil", "Imlil"),
    desc: T("Aldea bereber base de las ascensiones al Toubkal.", "Berber village and base camp for Toubkal climbs.", "Village berbère, camp de base des ascensions du Toubkal.") },
  { id: "vk-tinghir", cat: "villages", region: "south", coords: [31.51, -5.53], image: IMG["vk-tinghir"],
    name: T("Tinghir", "Tinghir", "Tinghir"),
    desc: T("Oasis exuberante a la entrada de las gargantas del Todra.", "Lush oasis at the entrance to the Todra gorges.", "Oasis luxuriante à l'entrée des gorges du Todra.") },
  { id: "vk-skoura", cat: "villages", region: "south", coords: [31.06, -6.55], image: IMG["vk-skoura"],
    name: T("Oasis de Skoura", "Skoura Oasis", "Oasis de Skoura"),
    desc: T("Palmeral salpicado de kasbahs de tierra junto al Atlas.", "Palm grove dotted with earthen kasbahs by the Atlas.", "Palmeraie parsemée de kasbahs de terre près de l'Atlas.") },
  { id: "vk-boumalne", cat: "villages", region: "south", coords: [31.36, -5.99], image: IMG["vk-boumalne"],
    name: T("Boumalne Dadès", "Boumalne Dades", "Boumalne Dadès"),
    desc: T("Puerta del valle del Dadès y sus formaciones rocosas.", "Gateway to the Dadès valley and its rock formations.", "Porte de la vallée du Dadès et ses formations rocheuses.") },
  { id: "vk-moulayidriss", cat: "villages", region: "imperial", coords: [34.05, -5.52], image: IMG["vk-moulayidriss"],
    name: T("Moulay Idriss", "Moulay Idriss", "Moulay Idriss"),
    desc: T("Pueblo sagrado en la colina, cuna del Marruecos islámico.", "Sacred hilltop town, cradle of Islamic Morocco.", "Village sacré perché, berceau du Maroc islamique.") },
  { id: "vk-asilah", cat: "villages", region: "north", coords: [35.46, -6.03], image: IMG["vk-asilah"],
    name: T("Asilah", "Asilah", "Asilah"),
    desc: T("Pueblo costero amurallado de murales y callejones blancos.", "Walled coastal town of murals and white alleys.", "Village côtier fortifié aux fresques et ruelles blanches.") },
  { id: "vk-telouet", cat: "villages", region: "atlas", coords: [31.29, -7.24], image: IMG["vk-telouet"],
    name: T("Kasbah de Telouet", "Telouet Kasbah", "Kasbah de Télouet"),
    desc: T("Kasbah del Glaoui, joya olvidada en la ruta del Atlas.", "The Glaoui kasbah, a forgotten gem on the Atlas route.", "Kasbah du Glaoui, joyau oublié sur la route de l'Atlas.") },

  // ---- Desiertos ----
  { id: "de-ergchebbi", cat: "deserts", region: "sahara", coords: [31.1, -4.0], image: IMG["de-ergchebbi"],
    name: T("Erg Chebbi", "Erg Chebbi", "Erg Chebbi"),
    desc: T("Mar de dunas doradas que alcanzan los 150 m de altura.", "Sea of golden dunes rising up to 150 m high.", "Mer de dunes dorées atteignant 150 m de haut.") },
  { id: "de-ergchigaga", cat: "deserts", region: "sahara", coords: [29.92, -5.95], image: IMG["de-ergchigaga"],
    name: T("Erg Chigaga", "Erg Chigaga", "Erg Chigaga"),
    desc: T("Dunas salvajes y remotas, el Sáhara más auténtico.", "Wild, remote dunes — the most authentic Sahara.", "Dunes sauvages et reculées, le Sahara le plus authentique.") },
  { id: "de-agafay", cat: "deserts", region: "south", coords: [31.42, -8.2], image: IMG["de-agafay"],
    name: T("Desierto de Agafay", "Agafay Desert", "Désert d'Agafay"),
    desc: T("Desierto pedregoso a un paso de Marrakech.", "Stony desert just a short drive from Marrakech.", "Désert pierreux à deux pas de Marrakech.") },
  { id: "de-zagora", cat: "deserts", region: "sahara", coords: [30.33, -5.84], image: IMG["de-zagora"],
    name: T("Zagora", "Zagora", "Zagora"),
    desc: T("Punto de partida de las caravanas hacia Tombuctú.", "Departure point of the caravans towards Timbuktu.", "Point de départ des caravanes vers Tombouctou.") },
  { id: "de-draa", cat: "deserts", region: "sahara", coords: [30.0, -6.0], image: IMG["de-draa"],
    name: T("Hamada del Drâa", "Drâa Hamada", "Hamada du Drâa"),
    desc: T("Vasta hamada y palmerales a lo largo del río Drâa.", "Vast hamada and palm groves along the Drâa river.", "Vaste hamada et palmeraies le long de l'oued Drâa.") },

  // ---- Montañas y Valles ----
  { id: "mo-toubkal", cat: "mountains", region: "atlas", coords: [31.06, -7.92], image: IMG["mo-toubkal"],
    name: T("Monte Toubkal", "Mount Toubkal", "Mont Toubkal"),
    desc: T("El techo del norte de África, 4.167 m de altura.", "The roof of North Africa, 4,167 m high.", "Le toit de l'Afrique du Nord, 4 167 m d'altitude.") },
  { id: "mo-dades", cat: "mountains", region: "south", coords: [31.55, -5.9], image: IMG["mo-dades"],
    name: T("Valle del Dadès", "Dadès Valley", "Vallée du Dadès"),
    desc: T("Cañón de roca roja con curvas vertiginosas.", "Red-rock canyon with dizzying switchbacks.", "Canyon de roche rouge aux virages vertigineux.") },
  { id: "mo-todra", cat: "mountains", region: "south", coords: [31.59, -5.6], image: IMG["mo-todra"],
    name: T("Gargantas del Todra", "Todra Gorges", "Gorges du Todra"),
    desc: T("Imponentes paredes verticales de hasta 300 m.", "Towering vertical walls of up to 300 m.", "Imposantes parois verticales jusqu'à 300 m.") },
  { id: "mo-ourika", cat: "mountains", region: "atlas", coords: [31.36, -7.75], image: IMG["mo-ourika"],
    name: T("Valle del Ourika", "Ourika Valley", "Vallée de l'Ourika"),
    desc: T("Valle verde de cascadas a una hora de Marrakech.", "Green valley of waterfalls an hour from Marrakech.", "Vallée verdoyante de cascades à une heure de Marrakech.") },
  { id: "mo-draavalley", cat: "mountains", region: "south", coords: [30.6, -6.3], image: IMG["mo-draavalley"],
    name: T("Valle del Drâa", "Drâa Valley", "Vallée du Drâa"),
    desc: T("El mayor palmeral de Marruecos, oasis tras oasis.", "Morocco's largest palm grove, oasis after oasis.", "La plus grande palmeraie du Maroc, oasis après oasis.") },
  { id: "mo-mgoun", cat: "mountains", region: "atlas", coords: [31.5, -6.42], image: IMG["mo-mgoun"],
    name: T("Macizo del M'Goun", "M'Goun Massif", "Massif du M'Goun"),
    desc: T("Macizo remoto para el trekking de altura del Atlas.", "Remote massif for high-altitude Atlas trekking.", "Massif reculé pour le trekking d'altitude de l'Atlas.") },
  { id: "mo-ifrane", cat: "mountains", region: "atlas", coords: [33.53, -5.11], image: IMG["mo-ifrane"],
    name: T("Cedros de Ifrane", "Ifrane Cedars", "Cèdres d'Ifrane"),
    desc: T("Estación alpina y cedros del Medio Atlas, 'la Suiza marroquí'.", "Alpine resort and Middle Atlas cedars, the 'Moroccan Switzerland'.", "Station alpine et cèdres du Moyen Atlas, la « Suisse marocaine ».") },
  { id: "mo-rif", cat: "mountains", region: "north", coords: [34.9, -4.9], image: IMG["mo-rif"],
    name: T("Montañas del Rif", "Rif Mountains", "Montagnes du Rif"),
    desc: T("Montañas verdes del norte salpicadas de pueblos bereberes.", "Green northern mountains dotted with Berber villages.", "Montagnes vertes du nord parsemées de villages berbères.") },

  // ---- Playas y Costa ----
  { id: "be-essaouira", cat: "beaches", region: "coast", coords: [31.5, -9.78], image: IMG["be-essaouira"],
    name: T("Playa de Essaouira", "Essaouira Beach", "Plage d'Essaouira"),
    desc: T("Larga playa de viento ideal para kitesurf y paseos.", "Long, windy beach ideal for kitesurfing and strolls.", "Longue plage venteuse idéale pour le kitesurf et les balades.") },
  { id: "be-agadir", cat: "beaches", region: "coast", coords: [30.41, -9.6], image: IMG["be-agadir"],
    name: T("Playa de Agadir", "Agadir Beach", "Plage d'Agadir"),
    desc: T("Bahía protegida de arena dorada y paseo marítimo.", "Sheltered bay of golden sand and a seaside promenade.", "Baie abritée de sable doré et promenade en bord de mer.") },
  { id: "be-legzira", cat: "beaches", region: "coast", coords: [29.55, -10.07], image: IMG["be-legzira"],
    name: T("Playa de Legzira", "Legzira Beach", "Plage de Legzira"),
    desc: T("Playa salvaje famosa por sus arcos de roca rojiza.", "Wild beach famous for its reddish rock arches.", "Plage sauvage célèbre pour ses arches de roche rougeâtre.") },
  { id: "be-taghazout", cat: "beaches", region: "coast", coords: [30.54, -9.71], image: IMG["be-taghazout"],
    name: T("Taghazout (surf)", "Taghazout (surf)", "Taghazout (surf)"),
    desc: T("Pueblo surfero de olas legendarias y ambiente relajado.", "Surf village with legendary waves and a laid-back vibe.", "Village de surf aux vagues légendaires et à l'ambiance détendue.") },
  { id: "be-saidia", cat: "beaches", region: "north", coords: [35.09, -2.23], image: IMG["be-saidia"],
    name: T("Saïdia (Mediterráneo)", "Saïdia (Mediterranean)", "Saïdia (Méditerranée)"),
    desc: T("Extensa playa mediterránea conocida como 'la Perla Azul'.", "Vast Mediterranean beach known as the 'Blue Pearl'.", "Vaste plage méditerranéenne surnommée « la Perle Bleue ».") },
  { id: "be-dakhla", cat: "beaches", region: "coast", coords: [23.71, -15.93], image: IMG["be-dakhla"],
    name: T("Dakhla", "Dakhla", "Dakhla"),
    desc: T("Laguna turquesa del sur, paraíso del kitesurf.", "Turquoise southern lagoon, a kitesurfing paradise.", "Lagune turquoise du sud, paradis du kitesurf.") },

  // ---- Monumentos e Historia ----
  { id: "mn-volubilis", cat: "monuments", region: "imperial", coords: [34.07, -5.55], image: IMG["mn-volubilis"],
    name: T("Volubilis (romano)", "Volubilis (Roman)", "Volubilis (romain)"),
    desc: T("Ruinas romanas con mosaicos, Patrimonio de la Humanidad.", "Roman ruins with mosaics, a World Heritage site.", "Ruines romaines aux mosaïques, patrimoine mondial.") },
  { id: "mn-koutoubia", cat: "monuments", region: "imperial", coords: [31.624, -7.993], image: IMG["mn-koutoubia"],
    name: T("Mezquita Koutoubia", "Koutoubia Mosque", "Mosquée Koutoubia"),
    desc: T("El gran alminar almohade que domina Marrakech.", "The great Almohad minaret towering over Marrakech.", "Le grand minaret almohade dominant Marrakech.") },
  { id: "mn-feselbali", cat: "monuments", region: "imperial", coords: [34.06, -4.98], image: IMG["mn-feselbali"],
    name: T("Medina de Fez el Bali", "Fez el Bali medina", "Médina de Fès el-Bali"),
    desc: T("Casco antiguo de Fez, dédalo medieval sin coches.", "Fez old town, a car-free medieval labyrinth.", "Vieille ville de Fès, labyrinthe médiéval sans voitures.") },
  { id: "mn-saadies", cat: "monuments", region: "imperial", coords: [31.618, -7.989], image: IMG["mn-saadies"],
    name: T("Tumbas Saadíes", "Saadian Tombs", "Tombeaux saadiens"),
    desc: T("Mausoleo del s. XVI con tumbas ricamente decoradas.", "16th-century mausoleum with richly decorated tombs.", "Mausolée du XVIe s. aux tombeaux richement décorés.") },
  { id: "mn-bahia", cat: "monuments", region: "imperial", coords: [31.621, -7.983], image: IMG["mn-bahia"],
    name: T("Palacio Bahía", "Bahia Palace", "Palais de la Bahia"),
    desc: T("Palacio del s. XIX, obra maestra del arte marroquí.", "19th-century palace, a masterpiece of Moroccan art.", "Palais du XIXe s., chef-d'œuvre de l'art marocain.") },
  { id: "mn-babmansour", cat: "monuments", region: "imperial", coords: [33.892, -5.564], image: IMG["mn-babmansour"],
    name: T("Bab Mansour (Meknès)", "Bab Mansour (Meknes)", "Bab Mansour (Meknès)"),
    desc: T("La puerta monumental más bella del mundo islámico.", "The most beautiful monumental gate in the Islamic world.", "La plus belle porte monumentale du monde islamique.") },
  { id: "mn-bouinania", cat: "monuments", region: "imperial", coords: [34.064, -4.978], image: IMG["mn-bouinania"],
    name: T("Medersa Bou Inania", "Bou Inania Madrasa", "Médersa Bou Inania"),
    desc: T("Madraza del s. XIV, cumbre de la arquitectura meriní.", "14th-century madrasa, a peak of Marinid architecture.", "Médersa du XIVe s., sommet de l'architecture mérinide.") },
  { id: "mn-skala", cat: "monuments", region: "coast", coords: [31.513, -9.772], image: IMG["mn-skala"],
    name: T("Murallas de Essaouira", "Essaouira ramparts", "Remparts d'Essaouira"),
    desc: T("Bastiones marinos portugueses sobre el océano.", "Portuguese sea bastions overlooking the ocean.", "Bastions maritimes portugais surplombant l'océan.") },

  // ---- Atracciones Turísticas ----
  { id: "at-jemaaelfna", cat: "attractions", region: "imperial", coords: [31.626, -7.989], image: IMG["at-jemaaelfna"],
    name: T("Plaza Jemaa el-Fna", "Jemaa el-Fna square", "Place Jemaa el-Fna"),
    desc: T("La plaza más célebre de Marruecos, espectáculo permanente.", "Morocco's most famous square, a permanent spectacle.", "La place la plus célèbre du Maroc, spectacle permanent.") },
  { id: "at-majorelle", cat: "attractions", region: "imperial", coords: [31.641, -8.003], image: IMG["at-majorelle"],
    name: T("Jardín Majorelle", "Majorelle Garden", "Jardin Majorelle"),
    desc: T("Jardín botánico azul cobalto rescatado por Yves Saint Laurent.", "Cobalt-blue botanical garden saved by Yves Saint Laurent.", "Jardin botanique bleu cobalt sauvé par Yves Saint Laurent.") },
  { id: "at-zocos", cat: "attractions", region: "imperial", coords: [31.63, -7.985], image: IMG["at-zocos"],
    name: T("Zocos de Marrakech", "Marrakech souks", "Souks de Marrakech"),
    desc: T("Laberinto de zocos con especias, cuero y artesanía.", "Maze of souks with spices, leather and crafts.", "Dédale de souks aux épices, cuir et artisanat.") },
  { id: "at-curtidurias", cat: "attractions", region: "imperial", coords: [34.066, -4.972], image: IMG["at-curtidurias"],
    name: T("Curtidurías de Fez", "Fez tanneries", "Tanneries de Fès"),
    desc: T("Las antiguas tenerías de Fez, teñido a mano centenario.", "Fez's ancient tanneries, centuries-old hand dyeing.", "Les anciennes tanneries de Fès, teinture à la main séculaire.") },
  { id: "at-ouzoud", cat: "attractions", region: "atlas", coords: [32.0, -6.72], image: IMG["at-ouzoud"],
    name: T("Cascadas de Ouzoud", "Ouzoud Waterfalls", "Cascades d'Ouzoud"),
    desc: T("Las cataratas más altas de Marruecos, 110 m de caída.", "Morocco's highest waterfalls, a 110 m drop.", "Les plus hautes cascades du Maroc, 110 m de chute.") },
  { id: "at-hercules", cat: "attractions", region: "north", coords: [35.76, -5.93], image: IMG["at-hercules"],
    name: T("Cuevas de Hércules", "Hercules Caves", "Grottes d'Hercule"),
    desc: T("Cuevas marinas legendarias frente al Atlántico.", "Legendary sea caves facing the Atlantic.", "Grottes marines légendaires face à l'Atlantique.") },
  { id: "at-atlasstudios", cat: "attractions", region: "south", coords: [30.91, -6.92], image: IMG["at-atlasstudios"],
    name: T("Atlas Studios (cine)", "Atlas Film Studios", "Studios de cinéma Atlas"),
    desc: T("Los mayores estudios de cine del mundo en pleno desierto.", "The world's largest film studios in the heart of the desert.", "Les plus grands studios de cinéma du monde au cœur du désert.") },
  { id: "at-dayetaoua", cat: "attractions", region: "atlas", coords: [33.62, -5.0], image: IMG["at-dayetaoua"],
    name: T("Lago Dayet Aoua", "Dayet Aoua Lake", "Lac Dayet Aoua"),
    desc: T("Apacible lago de montaña entre cedros del Medio Atlas.", "Peaceful mountain lake among Middle Atlas cedars.", "Paisible lac de montagne parmi les cèdres du Moyen Atlas.") },

  // ---- Experiencias Clave (no map coords) ----
  { id: "ex-bivouac", cat: "experiences", region: "sahara", image: IMG["ex-bivouac"],
    name: T("Noche en bivouac en el desierto", "Night in a desert bivouac", "Nuit en bivouac dans le désert"),
    desc: T("Dormir en una jaima bajo un cielo plagado de estrellas.", "Sleeping in a tent under a star-filled sky.", "Dormir sous une tente sous un ciel constellé d'étoiles.") },
  { id: "ex-camel", cat: "experiences", region: "sahara", image: IMG["ex-camel"],
    name: T("Ruta en dromedario", "Camel ride", "Balade à dos de dromadaire"),
    desc: T("Recorrer las dunas a lomos de un dromedario al atardecer.", "Crossing the dunes on a camel at sunset.", "Traverser les dunes à dos de dromadaire au coucher du soleil.") },
  { id: "ex-medina", cat: "experiences", region: "imperial", image: IMG["ex-medina"],
    name: T("Tour por la medina", "Medina tour", "Visite de la médina"),
    desc: T("Perderse entre zocos, aromas y artesanos de la medina.", "Getting lost among souks, scents and medina artisans.", "Se perdre parmi les souks, parfums et artisans de la médina.") },
  { id: "ex-4x4", cat: "experiences", region: "sahara", image: IMG["ex-4x4"],
    name: T("Ruta en 4x4 por el desierto", "4x4 desert route", "Route en 4x4 dans le désert"),
    desc: T("Aventura todoterreno por pistas y mares de arena.", "Off-road adventure across tracks and seas of sand.", "Aventure tout-terrain sur pistes et mers de sable.") },
  { id: "ex-oasis", cat: "experiences", region: "south", image: IMG["ex-oasis"],
    name: T("Visita a un oasis", "Visit to an oasis", "Visite d'une oasis"),
    desc: T("Caminar entre palmeras y acequias de un oasis vivo.", "Walking among palms and channels of a living oasis.", "Marcher parmi palmiers et séguias d'une oasis vivante.") },
  { id: "ex-berbertea", cat: "experiences", region: "atlas", image: IMG["ex-berbertea"],
    name: T("Té con una familia bereber", "Tea with a Berber family", "Thé avec une famille berbère"),
    desc: T("Compartir el té a la menta con una familia bereber.", "Sharing mint tea with a Berber family.", "Partager le thé à la menthe avec une famille berbère.") },
  { id: "ex-sunrise", cat: "experiences", region: "sahara", image: IMG["ex-sunrise"],
    name: T("Amanecer sobre las dunas", "Sunrise over the dunes", "Lever de soleil sur les dunes"),
    desc: T("Ver salir el sol sobre un océano de dunas.", "Watching the sun rise over an ocean of dunes.", "Voir le soleil se lever sur un océan de dunes.") },
  { id: "ex-hammam", cat: "experiences", region: "imperial", image: IMG["ex-hammam"],
    name: T("Hammam tradicional", "Traditional hammam", "Hammam traditionnel"),
    desc: T("Ritual de baño de vapor tradicional marroquí.", "Traditional Moroccan steam-bath ritual.", "Rituel de bain de vapeur traditionnel marocain.") },
  { id: "ex-trek", cat: "experiences", region: "atlas", image: IMG["ex-trek"],
    name: T("Senderismo en el Atlas", "Trekking in the Atlas", "Randonnée dans l'Atlas"),
    desc: T("Senderismo entre cumbres y aldeas del Atlas.", "Trekking among Atlas peaks and villages.", "Randonnée entre sommets et villages de l'Atlas.") },
  { id: "ex-cooking", cat: "experiences", region: "imperial", image: IMG["ex-cooking"],
    name: T("Clase de cocina marroquí", "Moroccan cooking class", "Cours de cuisine marocaine"),
    desc: T("Aprender a preparar un tajín en un taller local.", "Learning to cook a tagine in a local workshop.", "Apprendre à cuisiner un tajine dans un atelier local.") },
  { id: "ex-surf", cat: "experiences", region: "coast", image: IMG["ex-surf"],
    name: T("Surf en la costa atlántica", "Surf on the Atlantic coast", "Surf sur la côte atlantique"),
    desc: T("Coger olas en los célebres spots del Atlántico.", "Catching waves at the famous Atlantic spots.", "Prendre les vagues sur les spots célèbres de l'Atlantique.") },
  { id: "ex-sandboard", cat: "experiences", region: "sahara", image: IMG["ex-sandboard"],
    name: T("Sandboard en las dunas", "Sandboarding the dunes", "Sandboard sur les dunes"),
    desc: T("Deslizarse por las laderas de arena de las dunas.", "Sliding down the sandy slopes of the dunes.", "Glisser sur les pentes de sable des dunes.") },
];

export const TOTAL_PLACES = PLACES.length;

/* Levels / badges — unlocked by overall exploration percentage. */
export const LEVELS = [
  {
    id: "beginner", min: 0, icon: "Footprints", color: "#8C7B6B",
    name: T("Explorador Principiante", "Beginner Explorer", "Explorateur Débutant"),
    blurb: T("Tu aventura marroquí acaba de empezar.", "Your Moroccan adventure has just begun.", "Votre aventure marocaine ne fait que commencer."),
  },
  {
    id: "curious", min: 10, icon: "Compass", color: "#5A7F9C",
    name: T("Viajero Curioso", "Curious Traveller", "Voyageur Curieux"),
    blurb: T("Empiezas a descubrir los tesoros del país.", "You're starting to uncover the country's treasures.", "Vous commencez à découvrir les trésors du pays."),
  },
  {
    id: "atlas", min: 30, icon: "Mountain", color: "#5A6B4F",
    name: T("Aventurero del Atlas", "Atlas Adventurer", "Aventurier de l'Atlas"),
    blurb: T("Las montañas y los valles ya no tienen secretos.", "The mountains and valleys hold no more secrets.", "Les montagnes et vallées n'ont plus de secrets."),
  },
  {
    id: "desert", min: 50, icon: "Tent", color: "#C16542",
    name: T("Nómada del Desierto", "Desert Nomad", "Nomade du Désert"),
    blurb: T("Has cruzado las dunas y dormido bajo las estrellas.", "You've crossed the dunes and slept under the stars.", "Vous avez traversé les dunes et dormi sous les étoiles."),
  },
  {
    id: "conqueror", min: 75, icon: "Flag", color: "#A0432B",
    name: T("Conquistador de Marruecos", "Conqueror of Morocco", "Conquérant du Maroc"),
    blurb: T("Pocos rincones se te resisten ya.", "Few corners resist you now.", "Peu de recoins vous résistent désormais."),
  },
  {
    id: "legend", min: 100, icon: "Trophy", color: "#B8860B",
    name: T("Leyenda de Marruecos", "Legend of Morocco", "Légende du Maroc"),
    blurb: T("Lo has visto todo. Eres una leyenda viajera.", "You've seen it all. You're a travelling legend.", "Vous avez tout vu. Vous êtes une légende du voyage."),
  },
];

/* Resolve the achieved level + the next one to unlock, from a percentage. */
export const resolveLevel = (pct) => {
  let idx = 0;
  for (let i = 0; i < LEVELS.length; i += 1) {
    if (pct >= LEVELS[i].min) idx = i;
  }
  const current = LEVELS[idx];
  const next = idx < LEVELS.length - 1 ? LEVELS[idx + 1] : null;
  return { index: idx, current, next };
};
