// Trilingual placeholder copy for menu destinations using the StubPage template.

export const STUB_CONTENT = {
  appointment: {
    image: "https://images.unsplash.com/photo-1604940500627-d3f44d1d21c6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Cita previa", en: "Book an appointment", fr: "Prendre rendez-vous" },
    title:    { es: "Hablemos de tu próximo viaje a Marruecos.",
                en: "Let's talk about your next trip to Morocco.",
                fr: "Parlons de votre prochain voyage au Maroc." },
    body:     { es: "Reserva una llamada o una visita en nuestras oficinas. Un especialista te dedicará el tiempo necesario para diseñar contigo el viaje perfecto, sin prisas ni guiones automatizados.",
                en: "Book a call or an in-person meeting at our offices. A specialist will take the time to design the perfect journey with you — no rush, no scripts.",
                fr: "Réservez un appel ou une visite à nos bureaux. Un spécialiste prendra le temps de concevoir avec vous le voyage idéal — sans hâte, sans script." },
  },

  catalog: {
    image: "https://images.unsplash.com/photo-1570133435536-7ececf000ef6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Catálogo", en: "Catalogue", fr: "Catalogue" },
    title:    { es: "Catálogo de viajes a Marruecos.",
                en: "Our Morocco journeys catalogue.",
                fr: "Notre catalogue de voyages au Maroc." },
    body:     { es: "Explora nuestra colección completa de viajes organizados, escapadas cortas, aventuras y salidas en grupo por todo Marruecos.",
                en: "Explore our complete collection of curated trips, short escapes, adventures and group departures across Morocco.",
                fr: "Découvrez notre collection complète de voyages organisés, escapades, aventures et départs en groupe à travers le Maroc." },
  },

  tourSouth: {
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Sur de Marruecos", en: "Southern Morocco", fr: "Sud du Maroc" },
    title:    { es: "La magia del Sur: Sáhara, Atlas y oasis.",
                en: "The magic of the South: Sahara, Atlas and oases.",
                fr: "La magie du Sud : Sahara, Atlas et oasis." },
    body:     { es: "Rutas que combinan el desierto del Sáhara, las montañas del Alto Atlas, oasis escondidos y aldeas tradicionales llenas de historia.",
                en: "Routes weaving together the Sahara, the High Atlas, hidden oases and traditional villages full of history.",
                fr: "Des itinéraires mêlant Sahara, Haut Atlas, oasis secrètes et villages traditionnels chargés d'histoire." },
  },
  tourFull: {
    image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Marruecos al completo", en: "Full Morocco", fr: "Maroc intégral" },
    title:    { es: "Marruecos al completo, de norte a sur.",
                en: "Morocco from north to south.",
                fr: "Le Maroc du nord au sud." },
    body:     { es: "Rutas completas por todo el país descubriendo ciudades imperiales, el desierto y las montañas del Atlas a tu ritmo.",
                en: "Complete routes across the entire country — imperial cities, desert and Atlas mountains at your own pace.",
                fr: "Des itinéraires complets à travers tout le pays — cités impériales, désert et Atlas à votre rythme." },
  },
  tourShort: {
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Escapadas", en: "Short escapes", fr: "Escapades" },
    title:    { es: "Escapadas cortas por Marruecos.",
                en: "Short escapes across Morocco.",
                fr: "Escapades courtes au Maroc." },
    body:     { es: "Escapadas cuidadosamente diseñadas para quienes tienen pocos días pero quieren vivir la esencia de Marruecos.",
                en: "Carefully designed escapes for those with limited days who still want to live the essence of Morocco.",
                fr: "Des escapades soigneusement conçues pour ceux qui ont peu de temps mais veulent vivre l'essence du Maroc." },
  },
  tourNorth: {
    image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Norte de Marruecos", en: "Northern Morocco", fr: "Nord du Maroc" },
    title:    { es: "La riqueza y belleza del Norte.",
                en: "The richness and beauty of the North.",
                fr: "La richesse et la beauté du Nord." },
    body:     { es: "Descubre ciudades blancas y azules, medinas históricas, fortificaciones y paisajes mediterráneos.",
                en: "Discover blue and white towns, historic medinas, fortifications and Mediterranean landscapes.",
                fr: "Découvrez des villes bleues et blanches, des médinas historiques, des fortifications et des paysages méditerranéens." },
  },
  tourAdventure: {
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Aventura", en: "Adventure", fr: "Aventure" },
    title:    { es: "Viajes de aventura por Marruecos.",
                en: "Adventure tours across Morocco.",
                fr: "Voyages d'aventure au Maroc." },
    body:     { es: "Descubre nuestras propuestas de viajes de aventura, ya sea encima de una moto de enduro o recorriendo Marruecos a pie a través de rutas de trekking únicas.",
                en: "Discover our adventure tours, whether on an enduro motorcycle or hiking unique trekking routes across Morocco.",
                fr: "Découvrez nos voyages d'aventure, en moto d'enduro ou à pied à travers des itinéraires de trekking uniques au Maroc." },
  },
  upcomingDepartures: {
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Próximas salidas", en: "Upcoming departures", fr: "Prochains départs" },
    title:    { es: "Próximas salidas a Marruecos.",
                en: "Upcoming Morocco group departures.",
                fr: "Prochains départs en groupe au Maroc." },
    body:     { es: "Circuitos organizados con fechas cerradas y salidas en grupo durante Semana Santa, verano, fin de año y otras ocasiones especiales.",
                en: "Curated group departures with fixed dates throughout Easter, summer, New Year and other special occasions.",
                fr: "Départs en groupe à dates fixes pendant Pâques, l'été, le Nouvel An et d'autres occasions spéciales." },
  },
  tourBespoke: {
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Viajes a medida", en: "Tailor-made tours", fr: "Voyages sur mesure" },
    title:    { es: "Un viaje pensado exclusivamente para ti.",
                en: "A journey designed exclusively for you.",
                fr: "Un voyage pensé exclusivement pour vous." },
    body:     { es: "Cuéntanos cómo te gusta viajar y diseñaremos cada detalle: itinerario, alojamientos, experiencias, transporte y ritmo. Sin plantillas.",
                en: "Tell us how you love to travel and we'll design every detail — itinerary, accommodations, experiences, transport, pace. No templates.",
                fr: "Dites-nous comment vous aimez voyager et nous concevrons chaque détail — itinéraire, hébergements, expériences, transports, rythme. Aucun modèle." },
  },

  about: {
    image: "https://images.unsplash.com/photo-1604940500627-d3f44d1d21c6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Equipo", en: "The team", fr: "L'équipe" },
    title:    { es: "El equipo detrás de Xaluca Tours.",
                en: "The team behind Xaluca Tours.",
                fr: "L'équipe derrière Xaluca Tours." },
    body:     { es: "Más de 30 años creando viajes en Marruecos. Combinamos hospitalidad local con planificación premium — y la pasión de un equipo que vive el Sur cada día.",
                en: "Over 30 years crafting journeys in Morocco. We combine local hospitality with premium planning — and the passion of a team that lives the South every day.",
                fr: "Plus de 30 ans à créer des voyages au Maroc. Nous allions hospitalité locale et planification haut de gamme — et la passion d'une équipe qui vit le Sud au quotidien." },
  },
  whatWeDo: {
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "¿Qué hacemos?", en: "What we do", fr: "Ce que nous faisons" },
    title:    { es: "Diseñamos viajes a medida por Marruecos.",
                en: "We design tailor-made journeys across Morocco.",
                fr: "Nous concevons des voyages sur mesure au Maroc." },
    body:     { es: "Itinerarios, alojamientos, guías locales, transporte privado, experiencias auténticas, seguros y asistencia 24/7. Te acompañamos antes, durante y después del viaje.",
                en: "Itineraries, accommodations, local guides, private transport, authentic experiences, insurance and 24/7 assistance. We're with you before, during and after the trip.",
                fr: "Itinéraires, hébergements, guides locaux, transports privés, expériences authentiques, assurances et assistance 24/7. Avant, pendant et après le voyage." },
  },
  whatToSee: {
    image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "¿Qué ver en Marruecos?", en: "What to see in Morocco", fr: "Que voir au Maroc" },
    title:    { es: "Una guía honesta para descubrir Marruecos.",
                en: "An honest guide to discovering Morocco.",
                fr: "Un guide honnête pour découvrir le Maroc." },
    body:     { es: "Cordilleras legendarias, desiertos infinitos, ciudades imperiales, medinas antiguas, costas atlánticas y oasis llenos de palmeras. Te ayudamos a decidir qué es esencial para ti.",
                en: "Legendary mountains, endless deserts, imperial cities, ancient medinas, Atlantic coasts and palm-filled oases. We help you decide what's essential for you.",
                fr: "Montagnes légendaires, déserts infinis, cités impériales, médinas anciennes, côtes atlantiques et oasis de palmiers. Nous vous aidons à choisir ce qui est essentiel pour vous." },
  },
  events: {
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Incentivos", en: "Incentives", fr: "Incentives" },
    title:    { es: "Eventos corporativos & viajes de incentivo.",
                en: "Corporate events & incentive trips.",
                fr: "Événements d'entreprise & voyages incentives." },
    body:     { es: "Convenciones, viajes de incentivo, lanzamientos y bodas en lugares únicos — del desierto a las medinas, con la logística cuidada al milímetro.",
                en: "Conventions, incentive trips, product launches and weddings in unique venues — from the desert to ancient medinas, with logistics planned to the smallest detail.",
                fr: "Conventions, voyages incentives, lancements et mariages dans des lieux uniques — du désert aux médinas anciennes, avec une logistique millimétrée." },
  },
  morocco: {
    image: "https://images.unsplash.com/photo-1473625247510-8ceb1760943f?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Marruecos", en: "Morocco", fr: "Maroc" },
    title:    { es: "Un país de contrastes infinitos.",
                en: "A country of endless contrasts.",
                fr: "Un pays aux contrastes infinis." },
    body:     { es: "De Marrakech a Merzouga, de Fez a la ruta de las Kasbahs — Marruecos ofrece experiencias culturales, gastronómicas y de aventura inolvidables.",
                en: "From Marrakech to Merzouga, from Fez to the Route of the Kasbahs — Morocco offers unforgettable cultural, gastronomic and adventure experiences.",
                fr: "De Marrakech à Merzouga, de Fès à la Route des Kasbahs — le Maroc offre des expériences culturelles, gastronomiques et d'aventure inoubliables." },
  },
  contact: {
    image: "https://images.unsplash.com/photo-1604940500627-d3f44d1d21c6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Contacto", en: "Contact", fr: "Contact" },
    title:    { es: "Hablemos. Te respondemos en menos de 24 horas.",
                en: "Let's talk. We reply within 24 hours.",
                fr: "Parlons. Nous répondons en moins de 24 heures." },
    body:     { es: "Rellena el formulario o escríbenos directamente. Una persona real diseñará tu viaje contigo — sin embudos automáticos.",
                en: "Fill out the form or write to us directly. A real person will design your trip with you — no automated funnels.",
                fr: "Remplissez le formulaire ou écrivez-nous directement. Une personne réelle concevra votre voyage avec vous — sans entonnoir automatisé." },
  },
};
