// Trilingual placeholder copy for menu destinations that share the StubPage template.

export const STUB_CONTENT = {
  appointment: {
    image: "https://images.unsplash.com/photo-1604940500627-d3f44d1d21c6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Cita previa", en: "Book an appointment", fr: "Prendre rendez-vous" },
    title:    { es: "Hablemos de tu próximo viaje a Marruecos.",
                en: "Let's talk about your next trip to Morocco.",
                fr: "Parlons de votre prochain voyage au Maroc." },
    body:     { es: "Reserva una llamada o una visita en nuestras oficinas. Un especialista te dedicará el tiempo necesario para diseñar contigo el viaje perfecto, sin prisas ni guiones automatizados.",
                en: "Book a call or an in-person meeting at our offices. A specialist will take the time to design the perfect journey with you — no rush, no scripts.",
                fr: "Réservez un appel ou une visite à nos bureaux. Un spécialiste prendra le temps de concevoir avec vous le voyage idéal — sans hâte, sans script." },
  },

  tourAll: {
    image: "https://images.unsplash.com/photo-1570133435536-7ececf000ef6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Catálogo · Todos los viajes", en: "Catalogue · All tours", fr: "Catalogue · Tous les voyages" },
    title:    { es: "Todos nuestros itinerarios por Marruecos.",
                en: "Every itinerary we craft across Morocco.",
                fr: "Tous nos itinéraires à travers le Maroc." },
    body:     { es: "Explora la colección completa de itinerarios curados por nuestro equipo. Cada uno es un punto de partida que adaptaremos a tus intereses, tu ritmo y tu presupuesto.",
                en: "Explore the full collection of itineraries curated by our team. Each one is a starting point we'll tailor to your interests, pace and budget.",
                fr: "Découvrez la collection complète d'itinéraires conçus par notre équipe. Chacun est un point de départ que nous adapterons à vos envies, votre rythme et votre budget." },
  },
  tourSouth: {
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Sur de Marruecos", en: "Southern Morocco", fr: "Sud du Maroc" },
    title:    { es: "La magia del Sur: Sáhara, Atlas y oasis.",
                en: "The magic of the South: Sahara, Atlas and oases.",
                fr: "La magie du Sud : Sahara, Atlas et oasis." },
    body:     { es: "Rutas que combinan el desierto del Sáhara, las montañas del Alto Atlas, oasis escondidos y aldeas tradicionales llenas de historia.",
                en: "Routes weaving together the Sahara, the High Atlas, hidden oases and traditional villages full of history.",
                fr: "Des itinéraires mêlant Sahara, Haut Atlas, oasis secrètes et villages traditionnels chargés d'histoire." },
  },
  tourFull: {
    image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Marruecos al completo", en: "Full Morocco", fr: "Maroc intégral" },
    title:    { es: "El país entero, de norte a sur.",
                en: "The whole country, from north to south.",
                fr: "Le pays entier, du nord au sud." },
    body:     { es: "Ciudades imperiales, costas atlánticas, desiertos infinitos y aldeas remotas — el recorrido completo de Marruecos a tu ritmo.",
                en: "Imperial cities, Atlantic coasts, endless desert and remote villages — the full sweep of Morocco at your pace.",
                fr: "Cités impériales, côtes atlantiques, déserts infinis et villages reculés — la traversée complète du Maroc à votre rythme." },
  },
  tourShort: {
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Escapadas cortas", en: "Short escapes", fr: "Escapades courtes" },
    title:    { es: "Marruecos esencial en pocos días.",
                en: "Essential Morocco in just a few days.",
                fr: "Le Maroc essentiel en quelques jours." },
    body:     { es: "Para quienes tienen poco tiempo y mucho deseo. Itinerarios cortos cuidadosamente diseñados para vivir lo más auténtico de Marruecos.",
                en: "For those with little time and great desire. Short, carefully designed itineraries to live the most authentic side of Morocco.",
                fr: "Pour ceux qui ont peu de temps et beaucoup d'envie. Des itinéraires courts pensés pour vivre le Maroc le plus authentique." },
  },
  tourNorth: {
    image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Norte de Marruecos", en: "Northern Morocco", fr: "Nord du Maroc" },
    title:    { es: "Pueblos azules, medinas antiguas, mosaicos romanos.",
                en: "Blue towns, ancient medinas, Roman mosaics.",
                fr: "Villages bleus, médinas anciennes, mosaïques romaines." },
    body:     { es: "Descubre Chefchaouen, Fez, Tánger y la costa atlántica: una mezcla fascinante de texturas, aromas y culturas.",
                en: "Discover Chefchaouen, Fez, Tangier and the Atlantic coast: a fascinating blend of textures, aromas and cultures.",
                fr: "Découvrez Chefchaouen, Fès, Tanger et la côte atlantique : un mélange fascinant de textures, d'arômes et de cultures." },
  },
  tourFeatured: {
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Viajes destacados", en: "Featured tours", fr: "Voyages phares" },
    title:    { es: "Nuestros viajes más queridos.",
                en: "The journeys our travellers love most.",
                fr: "Les voyages que nos voyageurs adorent le plus." },
    body:     { es: "Una selección de los itinerarios más solicitados — cuidadosamente equilibrados entre cultura, naturaleza y experiencias auténticas.",
                en: "A selection of our most-requested itineraries — carefully balanced between culture, nature and authentic experiences.",
                fr: "Une sélection de nos itinéraires les plus demandés — équilibrés entre culture, nature et expériences authentiques." },
  },
  tourAdventure: {
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Aventura", en: "Adventure", fr: "Aventure" },
    title:    { es: "Expediciones 4x4, Toubkal y senderos perdidos.",
                en: "4x4 expeditions, Toubkal summits and lost trails.",
                fr: "Expéditions 4x4, ascensions du Toubkal et sentiers perdus." },
    body:     { es: "Para viajeros que buscan adrenalina y paisajes salvajes. Aventuras diseñadas con guías locales y un equipo logístico de primer nivel.",
                en: "For travellers chasing adrenaline and wild landscapes. Adventures designed with local guides and a top-tier logistics team.",
                fr: "Pour les voyageurs en quête d'adrénaline et de paysages sauvages. Aventures conçues avec des guides locaux et une équipe logistique de haut niveau." },
  },
  tourBespoke: {
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Viajes a medida", en: "Tailor-made tours", fr: "Voyages sur mesure" },
    title:    { es: "Un viaje pensado exclusivamente para ti.",
                en: "A journey designed exclusively for you.",
                fr: "Un voyage pensé exclusivement pour vous." },
    body:     { es: "Cuéntanos cómo te gusta viajar y diseñaremos cada detalle: itinerario, alojamientos, experiencias, transporte y ritmo. Sin plantillas.",
                en: "Tell us how you love to travel and we'll design every detail — itinerary, accommodations, experiences, transport, pace. No templates.",
                fr: "Dites-nous comment vous aimez voyager et nous concevrons chaque détail — itinéraire, hébergements, expériences, transports, rythme. Aucun modèle." },
  },

  about: {
    image: "https://images.unsplash.com/photo-1604940500627-d3f44d1d21c6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Sobre nosotros", en: "About us", fr: "À propos" },
    title:    { es: "Más de 30 años creando viajes en Marruecos.",
                en: "Over 30 years crafting journeys in Morocco.",
                fr: "Plus de 30 ans à créer des voyages au Maroc." },
    body:     { es: "Xaluca Tours forma parte del Grup Xaluca, una familia que ha hecho del Sur de Marruecos su hogar. Combinamos hospitalidad local y planificación premium.",
                en: "Xaluca Tours is part of Grup Xaluca, a family that has made Southern Morocco its home. We combine local hospitality with premium planning.",
                fr: "Xaluca Tours fait partie du Grup Xaluca, une famille qui a fait du Sud marocain sa maison. Nous allions hospitalité locale et planification haut de gamme." },
  },
  whatWeDo: {
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "¿Qué hacemos?", en: "What we do", fr: "Ce que nous faisons" },
    title:    { es: "Diseñamos viajes a medida por Marruecos.",
                en: "We design tailor-made journeys across Morocco.",
                fr: "Nous concevons des voyages sur mesure au Maroc." },
    body:     { es: "Itinerarios, alojamientos, guías locales, transporte privado, experiencias auténticas, seguros y asistencia 24/7. Te acompañamos antes, durante y después del viaje.",
                en: "Itineraries, accommodations, local guides, private transport, authentic experiences, insurance and 24/7 assistance. We're with you before, during and after the trip.",
                fr: "Itinéraires, hébergements, guides locaux, transports privés, expériences authentiques, assurances et assistance 24/7. Avant, pendant et après le voyage." },
  },
  whatToSee: {
    image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "¿Qué ver en Marruecos?", en: "What to see in Morocco", fr: "Que voir au Maroc" },
    title:    { es: "Una guía honesta para descubrir Marruecos.",
                en: "An honest guide to discovering Morocco.",
                fr: "Un guide honnête pour découvrir le Maroc." },
    body:     { es: "Cordilleras legendarias, desiertos infinitos, ciudades imperiales, medinas antiguas, costas atlánticas y oasis llenos de palmeras. Te ayudamos a decidir qué es esencial para ti.",
                en: "Legendary mountains, endless deserts, imperial cities, ancient medinas, Atlantic coasts and palm-filled oases. We help you decide what's essential for you.",
                fr: "Montagnes légendaires, déserts infinis, cités impériales, médinas anciennes, côtes atlantiques et oasis de palmiers. Nous vous aidons à choisir ce qui est essentiel pour vous." },
  },
  events: {
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Eventos & incentivos", en: "Events & incentives", fr: "Événements & incentives" },
    title:    { es: "Eventos corporativos memorables en Marruecos.",
                en: "Unforgettable corporate events in Morocco.",
                fr: "Événements d'entreprise mémorables au Maroc." },
    body:     { es: "Convenciones, viajes de incentivo, lanzamientos y bodas en lugares únicos — del desierto a las medinas, con la logística cuidada al milímetro.",
                en: "Conventions, incentive trips, product launches and weddings in unique venues — from the desert to ancient medinas, with logistics planned to the smallest detail.",
                fr: "Conventions, voyages incentives, lancements et mariages dans des lieux uniques — du désert aux médinas anciennes, avec une logistique millimétrée." },
  },
  hotels: {
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Nuestros hoteles", en: "Our hotels", fr: "Nos hôtels" },
    title:    { es: "La hospitalidad de Grup Xaluca en el sur.",
                en: "Grup Xaluca's hospitality in the south.",
                fr: "L'hospitalité de Grup Xaluca dans le sud." },
    body:     { es: "Nuestra colección de hoteles, kasbahs y campamentos en el sur de Marruecos: Erfoud, Merzouga, Ouarzazate, Tinghir y más. Calidad propia, garantizada.",
                en: "Our collection of hotels, kasbahs and camps across Southern Morocco: Erfoud, Merzouga, Ouarzazate, Tinghir and more. Our own quality, guaranteed.",
                fr: "Notre collection d'hôtels, kasbahs et camps dans le Sud marocain : Erfoud, Merzouga, Ouarzazate, Tinghir et bien plus. Notre propre qualité, garantie." },
  },
  morocco: {
    image: "https://images.unsplash.com/photo-1473625247510-8ceb1760943f?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Marruecos", en: "Morocco", fr: "Maroc" },
    title:    { es: "Un país de contrastes infinitos.",
                en: "A country of endless contrasts.",
                fr: "Un pays aux contrastes infinis." },
    body:     { es: "De Marrakech a Merzouga, de Fez a la ruta de las Kasbahs — Marruecos ofrece experiencias culturales, gastronómicas y de aventura inolvidables.",
                en: "From Marrakech to Merzouga, from Fez to the Route of the Kasbahs — Morocco offers unforgettable cultural, gastronomic and adventure experiences.",
                fr: "De Marrakech à Merzouga, de Fès à la Route des Kasbahs — le Maroc offre des expériences culturelles, gastronomiques et d'aventure inoubliables." },
  },
  contact: {
    image: "https://images.unsplash.com/photo-1604940500627-d3f44d1d21c6?auto=format&fit=crop&w=2000&q=85",
    overline: { es: "Contacto", en: "Contact", fr: "Contact" },
    title:    { es: "Hablemos. Te respondemos en menos de 24 horas.",
                en: "Let's talk. We reply within 24 hours.",
                fr: "Parlons. Nous répondons en moins de 24 heures." },
    body:     { es: "Rellena el formulario o escríbenos directamente. Una persona real diseñará tu viaje contigo — sin embudos automáticos.",
                en: "Fill out the form or write to us directly. A real person will design your trip with you — no automated funnels.",
                fr: "Remplissez le formulaire ou écrivez-nous directement. Une personne réelle concevra votre voyage avec vous — sans entonnoir automatisé." },
  },
};
